# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_proveedores.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_form_proveedores(object):
    def setupUi(self, form_proveedores):
        form_proveedores.setObjectName("form_proveedores")
        form_proveedores.resize(633, 481)
        form_proveedores.setStyleSheet("color: rgb(3, 3, 3);\n"
"background-color: rgb(44, 43, 58);\n"
"font: 10pt \"Liberation Sans\";\n"
"color: rgb(252, 252, 252);\n"
"selection-background-color: rgb(155, 155, 185);")
        self.gridLayout_2 = QtWidgets.QGridLayout(form_proveedores)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_15 = QtWidgets.QLabel(form_proveedores)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_2.addWidget(self.label_15)
        self.lne_cuit = QtWidgets.QLineEdit(form_proveedores)
        self.lne_cuit.setMinimumSize(QtCore.QSize(110, 0))
        self.lne_cuit.setMaximumSize(QtCore.QSize(110, 16777215))
        self.lne_cuit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lne_cuit.setText("")
        self.lne_cuit.setObjectName("lne_cuit")
        self.verticalLayout_2.addWidget(self.lne_cuit)
        self.horizontalLayout_15.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(form_proveedores)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.cbx_cliente = QtWidgets.QComboBox(form_proveedores)
        self.cbx_cliente.setObjectName("cbx_cliente")
        self.verticalLayout_3.addWidget(self.cbx_cliente)
        self.label_16 = QtWidgets.QLabel(form_proveedores)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_3.addWidget(self.label_16)
        self.lne_razon_social = QtWidgets.QLineEdit(form_proveedores)
        self.lne_razon_social.setMinimumSize(QtCore.QSize(350, 0))
        self.lne_razon_social.setMaximumSize(QtCore.QSize(350, 16777215))
        self.lne_razon_social.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lne_razon_social.setObjectName("lne_razon_social")
        self.verticalLayout_3.addWidget(self.lne_razon_social)
        self.horizontalLayout_15.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem)
        self.btn_buscar = QtWidgets.QPushButton(form_proveedores)
        self.btn_buscar.setMinimumSize(QtCore.QSize(0, 25))
        self.btn_buscar.setMaximumSize(QtCore.QSize(16777215, 25))
        self.btn_buscar.setStyleSheet("background-color: rgb(64, 63, 78);")
        self.btn_buscar.setObjectName("btn_buscar")
        self.horizontalLayout_15.addWidget(self.btn_buscar, 0, QtCore.Qt.AlignBottom)
        self.gridLayout_2.addLayout(self.horizontalLayout_15, 0, 0, 1, 1)
        self.btn_guardar = QtWidgets.QPushButton(form_proveedores)
        self.btn_guardar.setObjectName("btn_guardar")
        self.gridLayout_2.addWidget(self.btn_guardar, 2, 0, 1, 1, QtCore.Qt.AlignRight)
        self.tabWidget = QtWidgets.QTabWidget(form_proveedores)
        self.tabWidget.setStyleSheet("QTabWidget{\n"
"background-color: rgb(123, 121, 143);\n"
"}\n"
"QLineEdit {\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"}\n"
"QComboBox{\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lne_nombre = QtWidgets.QLineEdit(self.tab)
        self.lne_nombre.setMinimumSize(QtCore.QSize(200, 25))
        self.lne_nombre.setMaximumSize(QtCore.QSize(200, 25))
        self.lne_nombre.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_nombre.setObjectName("lne_nombre")
        self.horizontalLayout.addWidget(self.lne_nombre)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lne_razon_social_proveedor = QtWidgets.QLineEdit(self.tab)
        self.lne_razon_social_proveedor.setEnabled(True)
        self.lne_razon_social_proveedor.setMinimumSize(QtCore.QSize(400, 25))
        self.lne_razon_social_proveedor.setMaximumSize(QtCore.QSize(400, 25))
        self.lne_razon_social_proveedor.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_razon_social_proveedor.setObjectName("lne_razon_social_proveedor")
        self.horizontalLayout_2.addWidget(self.lne_razon_social_proveedor)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.lne_cuit_proveedor = QtWidgets.QLineEdit(self.tab)
        self.lne_cuit_proveedor.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_cuit_proveedor.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_cuit_proveedor.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_cuit_proveedor.setObjectName("lne_cuit_proveedor")
        self.horizontalLayout_3.addWidget(self.lne_cuit_proveedor)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.cbx_iva = QtWidgets.QComboBox(self.tab)
        self.cbx_iva.setMinimumSize(QtCore.QSize(0, 25))
        self.cbx_iva.setMaximumSize(QtCore.QSize(16777215, 25))
        self.cbx_iva.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cbx_iva.setObjectName("cbx_iva")
        self.cbx_iva.addItem("")
        self.cbx_iva.addItem("")
        self.cbx_iva.addItem("")
        self.cbx_iva.addItem("")
        self.cbx_iva.addItem("")
        self.horizontalLayout_4.addWidget(self.cbx_iva)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setMinimumSize(QtCore.QSize(95, 0))
        self.label_7.setMaximumSize(QtCore.QSize(95, 16777215))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.lne_ref = QtWidgets.QLineEdit(self.tab)
        self.lne_ref.setMinimumSize(QtCore.QSize(110, 25))
        self.lne_ref.setMaximumSize(QtCore.QSize(110, 25))
        self.lne_ref.setText("")
        self.lne_ref.setObjectName("lne_ref")
        self.horizontalLayout_5.addWidget(self.lne_ref)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem11)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 1)

        self.retranslateUi(form_proveedores)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(form_proveedores)
        form_proveedores.setTabOrder(self.lne_cuit, self.lne_razon_social)
        form_proveedores.setTabOrder(self.lne_razon_social, self.btn_buscar)
        form_proveedores.setTabOrder(self.btn_buscar, self.tabWidget)
        form_proveedores.setTabOrder(self.tabWidget, self.lne_nombre)
        form_proveedores.setTabOrder(self.lne_nombre, self.lne_razon_social_proveedor)
        form_proveedores.setTabOrder(self.lne_razon_social_proveedor, self.lne_cuit_proveedor)
        form_proveedores.setTabOrder(self.lne_cuit_proveedor, self.cbx_iva)
        form_proveedores.setTabOrder(self.cbx_iva, self.lne_ref)
        form_proveedores.setTabOrder(self.lne_ref, self.btn_guardar)

    def retranslateUi(self, form_proveedores):
        _translate = QtCore.QCoreApplication.translate
        form_proveedores.setWindowTitle(_translate("form_proveedores", "Proveedores"))
        self.label_15.setText(_translate("form_proveedores", "CUIT / CUIL: "))
        self.label_2.setText(_translate("form_proveedores", "Cliente:"))
        self.label_16.setText(_translate("form_proveedores", "Razón Social: "))
        self.btn_buscar.setText(_translate("form_proveedores", "Buscar"))
        self.btn_guardar.setText(_translate("form_proveedores", "Guardar"))
        self.label.setText(_translate("form_proveedores", "Nombre :"))
        self.label_3.setText(_translate("form_proveedores", "Razón Social :"))
        self.label_4.setText(_translate("form_proveedores", "CUIT / CUIL :"))
        self.label_5.setText(_translate("form_proveedores", "Condición Fte. IVA:"))
        self.cbx_iva.setItemText(0, _translate("form_proveedores", "Resp. Monotributo"))
        self.cbx_iva.setItemText(1, _translate("form_proveedores", "Resp. Inscripto"))
        self.cbx_iva.setItemText(2, _translate("form_proveedores", "Exento"))
        self.cbx_iva.setItemText(3, _translate("form_proveedores", "No Alcanzado"))
        self.cbx_iva.setItemText(4, _translate("form_proveedores", "Consumidor Final"))
        self.label_7.setText(_translate("form_proveedores", "Referencia: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("form_proveedores", "Proveedores"))

