# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_proveedores.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_form_proveedores(object):
    def setupUi(self, form_proveedores):
        form_proveedores.setObjectName("form_proveedores")
        form_proveedores.resize(750, 330)
        form_proveedores.setMinimumSize(QtCore.QSize(750, 300))
        form_proveedores.setMaximumSize(QtCore.QSize(750, 400))
        form_proveedores.setStyleSheet("font: 10pt \"Liberation Sans\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(156, 156, 156);\n"
"selection-background-color: rgb(164, 190, 221);\n"
"selection-color: rgb(0, 0, 0);")
        self.gridLayout_4 = QtWidgets.QGridLayout(form_proveedores)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_19 = QtWidgets.QLabel(form_proveedores)
        self.label_19.setMinimumSize(QtCore.QSize(80, 0))
        self.label_19.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_20.addWidget(self.label_19)
        self.lne_cuit = QtWidgets.QLineEdit(form_proveedores)
        self.lne_cuit.setMinimumSize(QtCore.QSize(110, 0))
        self.lne_cuit.setMaximumSize(QtCore.QSize(110, 16777215))
        self.lne_cuit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lne_cuit.setText("")
        self.lne_cuit.setObjectName("lne_cuit")
        self.horizontalLayout_20.addWidget(self.lne_cuit)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_20 = QtWidgets.QLabel(form_proveedores)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_23.addWidget(self.label_20)
        self.lne_razon_social = QtWidgets.QLineEdit(form_proveedores)
        self.lne_razon_social.setMinimumSize(QtCore.QSize(250, 0))
        self.lne_razon_social.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lne_razon_social.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lne_razon_social.setObjectName("lne_razon_social")
        self.horizontalLayout_23.addWidget(self.lne_razon_social)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_23)
        self.line_2 = QtWidgets.QFrame(form_proveedores)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_24.addWidget(self.line_2)
        self.btn_buscar = QtWidgets.QPushButton(form_proveedores)
        self.btn_buscar.setMinimumSize(QtCore.QSize(75, 50))
        self.btn_buscar.setMaximumSize(QtCore.QSize(75, 50))
        self.btn_buscar.setStyleSheet("background-color: rgb(119, 149, 177);")
        self.btn_buscar.setObjectName("btn_buscar")
        self.horizontalLayout_24.addWidget(self.btn_buscar)
        self.gridLayout_4.addLayout(self.horizontalLayout_24, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(form_proveedores)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(form_proveedores)
        self.tabWidget.setMinimumSize(QtCore.QSize(511, 201))
        self.tabWidget.setMaximumSize(QtCore.QSize(501, 201))
        self.tabWidget.setStyleSheet("QTabWidget{\n"
"background-color: rgb(123, 121, 143);\n"
"}\n"
"QLineEdit {\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"}\n"
"QComboBox{\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setMaximumSize(QtCore.QSize(120, 25))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setMinimumSize(QtCore.QSize(95, 0))
        self.label_7.setMaximumSize(QtCore.QSize(95, 16777215))
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lne_nombre = QtWidgets.QLineEdit(self.tab)
        self.lne_nombre.setMinimumSize(QtCore.QSize(350, 25))
        self.lne_nombre.setMaximumSize(QtCore.QSize(350, 25))
        self.lne_nombre.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_nombre.setObjectName("lne_nombre")
        self.gridLayout_2.addWidget(self.lne_nombre, 0, 0, 1, 1)
        self.lne_razon_social_proveedor = QtWidgets.QLineEdit(self.tab)
        self.lne_razon_social_proveedor.setEnabled(True)
        self.lne_razon_social_proveedor.setMinimumSize(QtCore.QSize(350, 25))
        self.lne_razon_social_proveedor.setMaximumSize(QtCore.QSize(350, 25))
        self.lne_razon_social_proveedor.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_razon_social_proveedor.setObjectName("lne_razon_social_proveedor")
        self.gridLayout_2.addWidget(self.lne_razon_social_proveedor, 1, 0, 1, 1)
        self.lne_cuit_proveedor = QtWidgets.QLineEdit(self.tab)
        self.lne_cuit_proveedor.setMinimumSize(QtCore.QSize(350, 25))
        self.lne_cuit_proveedor.setMaximumSize(QtCore.QSize(350, 25))
        self.lne_cuit_proveedor.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_cuit_proveedor.setObjectName("lne_cuit_proveedor")
        self.gridLayout_2.addWidget(self.lne_cuit_proveedor, 2, 0, 1, 1)
        self.cbx_iva = QtWidgets.QComboBox(self.tab)
        self.cbx_iva.setMinimumSize(QtCore.QSize(350, 25))
        self.cbx_iva.setMaximumSize(QtCore.QSize(350, 25))
        self.cbx_iva.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cbx_iva.setObjectName("cbx_iva")
        self.cbx_iva.addItem("")
        self.cbx_iva.addItem("")
        self.cbx_iva.addItem("")
        self.cbx_iva.addItem("")
        self.cbx_iva.addItem("")
        self.gridLayout_2.addWidget(self.cbx_iva, 3, 0, 1, 1)
        self.lne_ref = QtWidgets.QLineEdit(self.tab)
        self.lne_ref.setMinimumSize(QtCore.QSize(110, 25))
        self.lne_ref.setMaximumSize(QtCore.QSize(110, 25))
        self.lne_ref.setText("")
        self.lne_ref.setObjectName("lne_ref")
        self.gridLayout_2.addWidget(self.lne_ref, 4, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tw_proveedores = QtWidgets.QTableWidget(self.tab_2)
        self.tw_proveedores.setGeometry(QtCore.QRect(50, 10, 431, 151))
        self.tw_proveedores.setObjectName("tw_proveedores")
        self.tw_proveedores.setColumnCount(3)
        self.tw_proveedores.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_proveedores.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_proveedores.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_proveedores.setHorizontalHeaderItem(2, item)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_4.addWidget(self.tabWidget, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.btn_guardar = QtWidgets.QPushButton(form_proveedores)
        self.btn_guardar.setStyleSheet("background-color: rgb(119, 149, 177);")
        self.btn_guardar.setObjectName("btn_guardar")
        self.gridLayout_4.addWidget(self.btn_guardar, 3, 0, 1, 1)
        self.btn_eliminar = QtWidgets.QPushButton(form_proveedores)
        self.btn_eliminar.setObjectName("btn_eliminar")
        self.gridLayout_4.addWidget(self.btn_eliminar, 2, 1, 1, 1)

        self.retranslateUi(form_proveedores)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(form_proveedores)
        form_proveedores.setTabOrder(self.lne_cuit, self.lne_razon_social)
        form_proveedores.setTabOrder(self.lne_razon_social, self.btn_buscar)
        form_proveedores.setTabOrder(self.btn_buscar, self.tabWidget)
        form_proveedores.setTabOrder(self.tabWidget, self.lne_nombre)
        form_proveedores.setTabOrder(self.lne_nombre, self.lne_razon_social_proveedor)
        form_proveedores.setTabOrder(self.lne_razon_social_proveedor, self.lne_cuit_proveedor)
        form_proveedores.setTabOrder(self.lne_cuit_proveedor, self.cbx_iva)
        form_proveedores.setTabOrder(self.cbx_iva, self.lne_ref)
        form_proveedores.setTabOrder(self.lne_ref, self.btn_guardar)
        form_proveedores.setTabOrder(self.btn_guardar, self.tw_proveedores)

    def retranslateUi(self, form_proveedores):
        _translate = QtCore.QCoreApplication.translate
        form_proveedores.setWindowTitle(_translate("form_proveedores", "Proveedores"))
        self.label_19.setText(_translate("form_proveedores", "CUIT / CUIL: "))
        self.label_20.setText(_translate("form_proveedores", "Razón Social: "))
        self.btn_buscar.setText(_translate("form_proveedores", "Buscar"))
        self.label.setText(_translate("form_proveedores", "Nombre :"))
        self.label_3.setText(_translate("form_proveedores", "Razón Social :"))
        self.label_4.setText(_translate("form_proveedores", "CUIT / CUIL :"))
        self.label_5.setText(_translate("form_proveedores", "Condición Fte. IVA:"))
        self.label_7.setText(_translate("form_proveedores", "Referencia: "))
        self.cbx_iva.setItemText(0, _translate("form_proveedores", "Resp. Monotributo"))
        self.cbx_iva.setItemText(1, _translate("form_proveedores", "Resp. Inscripto"))
        self.cbx_iva.setItemText(2, _translate("form_proveedores", "Exento"))
        self.cbx_iva.setItemText(3, _translate("form_proveedores", "No Alcanzado"))
        self.cbx_iva.setItemText(4, _translate("form_proveedores", "Consumidor Final"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("form_proveedores", "Proveedores / Clientes"))
        item = self.tw_proveedores.horizontalHeaderItem(0)
        item.setText(_translate("form_proveedores", "Cuit/Cuil"))
        item = self.tw_proveedores.horizontalHeaderItem(1)
        item.setText(_translate("form_proveedores", "Nombre"))
        item = self.tw_proveedores.horizontalHeaderItem(2)
        item.setText(_translate("form_proveedores", "Razon Social"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("form_proveedores", "Lista de Proveedores / Clientes"))
        self.btn_guardar.setText(_translate("form_proveedores", "Guardar"))
        self.btn_eliminar.setText(_translate("form_proveedores", "Eliminar"))

