# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_libro_iva_compras.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_form_libro_iva_compras(object):
    def setupUi(self, form_libro_iva_compras):
        form_libro_iva_compras.setObjectName("form_libro_iva_compras")
        form_libro_iva_compras.resize(800, 600)
        form_libro_iva_compras.setMinimumSize(QtCore.QSize(800, 600))
        form_libro_iva_compras.setMaximumSize(QtCore.QSize(1920, 1080))
        form_libro_iva_compras.setStyleSheet("font: 10pt \"Liberation Sans\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(156, 156, 156);\n"
"selection-background-color: rgb(164, 190, 221);\n"
"selection-color: rgb(0, 0, 0);")
        self.gridLayout_2 = QtWidgets.QGridLayout(form_libro_iva_compras)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_15 = QtWidgets.QLabel(form_libro_iva_compras)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_2.addWidget(self.label_15)
        self.lne_cuit = QtWidgets.QLineEdit(form_libro_iva_compras)
        self.lne_cuit.setMinimumSize(QtCore.QSize(110, 0))
        self.lne_cuit.setMaximumSize(QtCore.QSize(110, 16777215))
        self.lne_cuit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lne_cuit.setText("")
        self.lne_cuit.setObjectName("lne_cuit")
        self.verticalLayout_2.addWidget(self.lne_cuit)
        self.horizontalLayout_15.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_16 = QtWidgets.QLabel(form_libro_iva_compras)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_3.addWidget(self.label_16)
        self.lne_razon_social = QtWidgets.QLineEdit(form_libro_iva_compras)
        self.lne_razon_social.setMinimumSize(QtCore.QSize(350, 0))
        self.lne_razon_social.setMaximumSize(QtCore.QSize(350, 16777215))
        self.lne_razon_social.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lne_razon_social.setObjectName("lne_razon_social")
        self.verticalLayout_3.addWidget(self.lne_razon_social)
        self.horizontalLayout_15.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem)
        self.btn_buscar = QtWidgets.QPushButton(form_libro_iva_compras)
        self.btn_buscar.setMinimumSize(QtCore.QSize(75, 50))
        self.btn_buscar.setMaximumSize(QtCore.QSize(75, 50))
        self.btn_buscar.setStyleSheet("background-color: rgb(119, 149, 177)")
        self.btn_buscar.setObjectName("btn_buscar")
        self.horizontalLayout_15.addWidget(self.btn_buscar, 0, QtCore.Qt.AlignBottom)
        self.gridLayout_2.addLayout(self.horizontalLayout_15, 0, 0, 1, 2)
        self.line = QtWidgets.QFrame(form_libro_iva_compras)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(form_libro_iva_compras)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.cbx_ejercicio = QtWidgets.QComboBox(form_libro_iva_compras)
        self.cbx_ejercicio.setMinimumSize(QtCore.QSize(150, 25))
        self.cbx_ejercicio.setMaximumSize(QtCore.QSize(150, 25))
        self.cbx_ejercicio.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cbx_ejercicio.setObjectName("cbx_ejercicio")
        self.horizontalLayout_3.addWidget(self.cbx_ejercicio)
        self.btn_buscar_2 = QtWidgets.QPushButton(form_libro_iva_compras)
        self.btn_buscar_2.setMinimumSize(QtCore.QSize(0, 25))
        self.btn_buscar_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.btn_buscar_2.setStyleSheet("background-color: rgb(119, 149, 177)")
        self.btn_buscar_2.setObjectName("btn_buscar_2")
        self.horizontalLayout_3.addWidget(self.btn_buscar_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(form_libro_iva_compras)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.cbx_mes = QtWidgets.QComboBox(form_libro_iva_compras)
        self.cbx_mes.setMinimumSize(QtCore.QSize(150, 25))
        self.cbx_mes.setMaximumSize(QtCore.QSize(150, 25))
        self.cbx_mes.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cbx_mes.setObjectName("cbx_mes")
        self.cbx_mes.addItem("")
        self.cbx_mes.addItem("")
        self.cbx_mes.addItem("")
        self.cbx_mes.addItem("")
        self.cbx_mes.addItem("")
        self.cbx_mes.addItem("")
        self.cbx_mes.addItem("")
        self.cbx_mes.addItem("")
        self.cbx_mes.addItem("")
        self.cbx_mes.addItem("")
        self.cbx_mes.addItem("")
        self.cbx_mes.addItem("")
        self.horizontalLayout_2.addWidget(self.cbx_mes)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 2, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(form_libro_iva_compras)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 3, 0, 1, 2)
        self.tabWidget = QtWidgets.QTabWidget(form_libro_iva_compras)
        self.tabWidget.setStyleSheet("QTabWidget{\n"
"background-color: rgb(123, 121, 143);\n"
"}\n"
"QLineEdit {\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"}\n"
"QComboBox{\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.tw_compras = QtWidgets.QTableWidget(self.tab)
        self.tw_compras.setStyleSheet("font: 9pt \"Liberation Sans\";")
        self.tw_compras.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tw_compras.setObjectName("tw_compras")
        self.tw_compras.setColumnCount(17)
        self.tw_compras.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_compras.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_compras.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_compras.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_compras.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_compras.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_compras.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_compras.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_compras.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_compras.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_compras.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_compras.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_compras.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_compras.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_compras.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_compras.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_compras.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_compras.setHorizontalHeaderItem(16, item)
        self.tw_compras.horizontalHeader().setDefaultSectionSize(110)
        self.gridLayout.addWidget(self.tw_compras, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lne_resultado_uno = QtWidgets.QLineEdit(self.tab)
        self.lne_resultado_uno.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_resultado_uno.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_resultado_uno.setObjectName("lne_resultado_uno")
        self.horizontalLayout_4.addWidget(self.lne_resultado_uno)
        self.lne_resultado_dos = QtWidgets.QLineEdit(self.tab)
        self.lne_resultado_dos.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_resultado_dos.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_resultado_dos.setObjectName("lne_resultado_dos")
        self.horizontalLayout_4.addWidget(self.lne_resultado_dos)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.btn_eliminar = QtWidgets.QPushButton(self.tab)
        self.btn_eliminar.setMinimumSize(QtCore.QSize(75, 25))
        self.btn_eliminar.setMaximumSize(QtCore.QSize(75, 25))
        self.btn_eliminar.setStyleSheet("background-color: rgb(119, 149, 177)")
        self.btn_eliminar.setObjectName("btn_eliminar")
        self.horizontalLayout.addWidget(self.btn_eliminar)
        self.btn_modificar = QtWidgets.QPushButton(self.tab)
        self.btn_modificar.setStyleSheet("background-color: rgb(119, 149, 177)")
        self.btn_modificar.setObjectName("btn_modificar")
        self.horizontalLayout.addWidget(self.btn_modificar, 0, QtCore.Qt.AlignRight)
        self.btn_nuevo = QtWidgets.QPushButton(self.tab)
        self.btn_nuevo.setStyleSheet("background-color: rgb(119, 149, 177)")
        self.btn_nuevo.setObjectName("btn_nuevo")
        self.horizontalLayout.addWidget(self.btn_nuevo, 0, QtCore.Qt.AlignRight)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 4, 0, 1, 2)

        self.retranslateUi(form_libro_iva_compras)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(form_libro_iva_compras)
        form_libro_iva_compras.setTabOrder(self.lne_cuit, self.lne_razon_social)
        form_libro_iva_compras.setTabOrder(self.lne_razon_social, self.btn_buscar)
        form_libro_iva_compras.setTabOrder(self.btn_buscar, self.cbx_ejercicio)
        form_libro_iva_compras.setTabOrder(self.cbx_ejercicio, self.btn_buscar_2)
        form_libro_iva_compras.setTabOrder(self.btn_buscar_2, self.cbx_mes)
        form_libro_iva_compras.setTabOrder(self.cbx_mes, self.tabWidget)
        form_libro_iva_compras.setTabOrder(self.tabWidget, self.tw_compras)
        form_libro_iva_compras.setTabOrder(self.tw_compras, self.lne_resultado_uno)
        form_libro_iva_compras.setTabOrder(self.lne_resultado_uno, self.lne_resultado_dos)
        form_libro_iva_compras.setTabOrder(self.lne_resultado_dos, self.btn_eliminar)
        form_libro_iva_compras.setTabOrder(self.btn_eliminar, self.btn_modificar)
        form_libro_iva_compras.setTabOrder(self.btn_modificar, self.btn_nuevo)

    def retranslateUi(self, form_libro_iva_compras):
        _translate = QtCore.QCoreApplication.translate
        form_libro_iva_compras.setWindowTitle(_translate("form_libro_iva_compras", "Libro IVA Compras"))
        self.label_15.setText(_translate("form_libro_iva_compras", "CUIT / CUIL: "))
        self.label_16.setText(_translate("form_libro_iva_compras", "Razón Social: "))
        self.btn_buscar.setText(_translate("form_libro_iva_compras", "Buscar"))
        self.label_2.setText(_translate("form_libro_iva_compras", "Ejercicio:"))
        self.btn_buscar_2.setText(_translate("form_libro_iva_compras", "Buscar"))
        self.label.setText(_translate("form_libro_iva_compras", "Mes:"))
        self.cbx_mes.setItemText(0, _translate("form_libro_iva_compras", "Enero"))
        self.cbx_mes.setItemText(1, _translate("form_libro_iva_compras", "Febrero"))
        self.cbx_mes.setItemText(2, _translate("form_libro_iva_compras", "Marzo"))
        self.cbx_mes.setItemText(3, _translate("form_libro_iva_compras", "Abril"))
        self.cbx_mes.setItemText(4, _translate("form_libro_iva_compras", "Mayo"))
        self.cbx_mes.setItemText(5, _translate("form_libro_iva_compras", "Junio"))
        self.cbx_mes.setItemText(6, _translate("form_libro_iva_compras", "Julio"))
        self.cbx_mes.setItemText(7, _translate("form_libro_iva_compras", "Agosto"))
        self.cbx_mes.setItemText(8, _translate("form_libro_iva_compras", "Septiembre"))
        self.cbx_mes.setItemText(9, _translate("form_libro_iva_compras", "Octubre"))
        self.cbx_mes.setItemText(10, _translate("form_libro_iva_compras", "Noviembre"))
        self.cbx_mes.setItemText(11, _translate("form_libro_iva_compras", "Diciembre"))
        item = self.tw_compras.horizontalHeaderItem(0)
        item.setText(_translate("form_libro_iva_compras", "Fecha"))
        item = self.tw_compras.horizontalHeaderItem(1)
        item.setText(_translate("form_libro_iva_compras", "N° Comprobante"))
        item = self.tw_compras.horizontalHeaderItem(2)
        item.setText(_translate("form_libro_iva_compras", "Tipo"))
        item = self.tw_compras.horizontalHeaderItem(3)
        item.setText(_translate("form_libro_iva_compras", "Ref"))
        item = self.tw_compras.horizontalHeaderItem(4)
        item.setText(_translate("form_libro_iva_compras", "Proveedor"))
        item = self.tw_compras.horizontalHeaderItem(5)
        item.setText(_translate("form_libro_iva_compras", "Cond. Fte. IVA"))
        item = self.tw_compras.horizontalHeaderItem(6)
        item.setText(_translate("form_libro_iva_compras", "CUIT"))
        item = self.tw_compras.horizontalHeaderItem(7)
        item.setText(_translate("form_libro_iva_compras", "10,5%"))
        item = self.tw_compras.horizontalHeaderItem(8)
        item.setText(_translate("form_libro_iva_compras", "21%"))
        item = self.tw_compras.horizontalHeaderItem(9)
        item.setText(_translate("form_libro_iva_compras", "27%"))
        item = self.tw_compras.horizontalHeaderItem(10)
        item.setText(_translate("form_libro_iva_compras", "MONOTRIBUTO"))
        item = self.tw_compras.horizontalHeaderItem(11)
        item.setText(_translate("form_libro_iva_compras", "No Grav./Op Exentas"))
        item = self.tw_compras.horizontalHeaderItem(12)
        item.setText(_translate("form_libro_iva_compras", "IVA"))
        item = self.tw_compras.horizontalHeaderItem(13)
        item.setText(_translate("form_libro_iva_compras", "Percep. IIBB"))
        item = self.tw_compras.horizontalHeaderItem(14)
        item.setText(_translate("form_libro_iva_compras", "Imp. Gasoil"))
        item = self.tw_compras.horizontalHeaderItem(15)
        item.setText(_translate("form_libro_iva_compras", "Percep. IVA"))
        item = self.tw_compras.horizontalHeaderItem(16)
        item.setText(_translate("form_libro_iva_compras", "TOTAL"))
        self.label_3.setText(_translate("form_libro_iva_compras", "Resultado: "))
        self.btn_eliminar.setText(_translate("form_libro_iva_compras", "Eliminar"))
        self.btn_modificar.setText(_translate("form_libro_iva_compras", "Actualizar"))
        self.btn_nuevo.setText(_translate("form_libro_iva_compras", "Nuevo"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("form_libro_iva_compras", "Libro IVA Compras "))

