# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_asiento.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_form_asiento(object):
    def setupUi(self, form_asiento):
        form_asiento.setObjectName("form_asiento")
        form_asiento.resize(622, 265)
        form_asiento.setStyleSheet("color: rgb(3, 3, 3);\n"
"background-color: rgb(44, 43, 58);\n"
"font: 10pt \"Liberation Sans\";\n"
"color: rgb(252, 252, 252);\n"
"selection-background-color: rgb(155, 155, 185);")
        self.gridLayout_2 = QtWidgets.QGridLayout(form_asiento)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_15 = QtWidgets.QLabel(form_asiento)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_2.addWidget(self.label_15)
        self.lne_cuit = QtWidgets.QLineEdit(form_asiento)
        self.lne_cuit.setMinimumSize(QtCore.QSize(110, 0))
        self.lne_cuit.setMaximumSize(QtCore.QSize(110, 16777215))
        self.lne_cuit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lne_cuit.setText("")
        self.lne_cuit.setObjectName("lne_cuit")
        self.verticalLayout_2.addWidget(self.lne_cuit)
        self.horizontalLayout_15.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_16 = QtWidgets.QLabel(form_asiento)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_3.addWidget(self.label_16)
        self.lne_razon_social = QtWidgets.QLineEdit(form_asiento)
        self.lne_razon_social.setMinimumSize(QtCore.QSize(350, 0))
        self.lne_razon_social.setMaximumSize(QtCore.QSize(350, 16777215))
        self.lne_razon_social.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lne_razon_social.setObjectName("lne_razon_social")
        self.verticalLayout_3.addWidget(self.lne_razon_social)
        self.horizontalLayout_15.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem)
        self.btn_buscar = QtWidgets.QPushButton(form_asiento)
        self.btn_buscar.setMinimumSize(QtCore.QSize(0, 25))
        self.btn_buscar.setMaximumSize(QtCore.QSize(16777215, 25))
        self.btn_buscar.setStyleSheet("background-color: rgb(64, 63, 78);")
        self.btn_buscar.setObjectName("btn_buscar")
        self.horizontalLayout_15.addWidget(self.btn_buscar, 0, QtCore.Qt.AlignBottom)
        self.gridLayout_2.addLayout(self.horizontalLayout_15, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(form_asiento)
        self.tabWidget.setStyleSheet("QTabWidget{\n"
"background-color: rgb(123, 121, 143);\n"
"}\n"
"QLineEdit {\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"}\n"
"QComboBox{\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.cbx_ejercicio = QtWidgets.QComboBox(self.tab)
        self.cbx_ejercicio.setMinimumSize(QtCore.QSize(250, 25))
        self.cbx_ejercicio.setMaximumSize(QtCore.QSize(250, 25))
        self.cbx_ejercicio.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.cbx_ejercicio.setObjectName("cbx_ejercicio")
        self.horizontalLayout_3.addWidget(self.cbx_ejercicio)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.cbx_mes = QtWidgets.QComboBox(self.tab)
        self.cbx_mes.setMinimumSize(QtCore.QSize(150, 25))
        self.cbx_mes.setMaximumSize(QtCore.QSize(150, 25))
        self.cbx_mes.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.cbx_mes.setObjectName("cbx_mes")
        self.cbx_mes.addItem("")
        self.cbx_mes.addItem("")
        self.cbx_mes.addItem("")
        self.cbx_mes.addItem("")
        self.cbx_mes.addItem("")
        self.cbx_mes.addItem("")
        self.cbx_mes.addItem("")
        self.cbx_mes.addItem("")
        self.cbx_mes.addItem("")
        self.cbx_mes.addItem("")
        self.cbx_mes.addItem("")
        self.cbx_mes.addItem("")
        self.horizontalLayout_4.addWidget(self.cbx_mes)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setMinimumSize(QtCore.QSize(50, 25))
        self.label_5.setMaximumSize(QtCore.QSize(50, 25))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.dte_fecha = QtWidgets.QDateEdit(self.tab)
        self.dte_fecha.setMinimumSize(QtCore.QSize(100, 25))
        self.dte_fecha.setMaximumSize(QtCore.QSize(100, 25))
        self.dte_fecha.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.dte_fecha.setObjectName("dte_fecha")
        self.horizontalLayout_5.addWidget(self.dte_fecha)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setMinimumSize(QtCore.QSize(75, 25))
        self.label_2.setMaximumSize(QtCore.QSize(75, 25))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lne_descripcion = QtWidgets.QLineEdit(self.tab)
        self.lne_descripcion.setMinimumSize(QtCore.QSize(475, 25))
        self.lne_descripcion.setMaximumSize(QtCore.QSize(475, 25))
        self.lne_descripcion.setText("")
        self.lne_descripcion.setObjectName("lne_descripcion")
        self.horizontalLayout_2.addWidget(self.lne_descripcion)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.btn_guardar = QtWidgets.QPushButton(form_asiento)
        self.btn_guardar.setMinimumSize(QtCore.QSize(0, 25))
        self.btn_guardar.setMaximumSize(QtCore.QSize(16777215, 25))
        self.btn_guardar.setStyleSheet("background-color: rgb(64, 63, 78);")
        self.btn_guardar.setObjectName("btn_guardar")
        self.gridLayout_2.addWidget(self.btn_guardar, 2, 0, 1, 1, QtCore.Qt.AlignRight)

        self.retranslateUi(form_asiento)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(form_asiento)
        form_asiento.setTabOrder(self.lne_cuit, self.lne_razon_social)
        form_asiento.setTabOrder(self.lne_razon_social, self.btn_buscar)
        form_asiento.setTabOrder(self.btn_buscar, self.tabWidget)
        form_asiento.setTabOrder(self.tabWidget, self.cbx_ejercicio)
        form_asiento.setTabOrder(self.cbx_ejercicio, self.cbx_mes)
        form_asiento.setTabOrder(self.cbx_mes, self.dte_fecha)
        form_asiento.setTabOrder(self.dte_fecha, self.lne_descripcion)
        form_asiento.setTabOrder(self.lne_descripcion, self.btn_guardar)

    def retranslateUi(self, form_asiento):
        _translate = QtCore.QCoreApplication.translate
        form_asiento.setWindowTitle(_translate("form_asiento", "Asiento"))
        self.label_15.setText(_translate("form_asiento", "CUIT / CUIL: "))
        self.label_16.setText(_translate("form_asiento", "Razón Social: "))
        self.btn_buscar.setText(_translate("form_asiento", "Buscar"))
        self.label_3.setText(_translate("form_asiento", "Ejercicio:"))
        self.label_4.setText(_translate("form_asiento", "Mes: "))
        self.cbx_mes.setItemText(0, _translate("form_asiento", "Enero"))
        self.cbx_mes.setItemText(1, _translate("form_asiento", "Febrero"))
        self.cbx_mes.setItemText(2, _translate("form_asiento", "Marzo"))
        self.cbx_mes.setItemText(3, _translate("form_asiento", "Abril"))
        self.cbx_mes.setItemText(4, _translate("form_asiento", "Mayo"))
        self.cbx_mes.setItemText(5, _translate("form_asiento", "Junio"))
        self.cbx_mes.setItemText(6, _translate("form_asiento", "Julio"))
        self.cbx_mes.setItemText(7, _translate("form_asiento", "Agosto"))
        self.cbx_mes.setItemText(8, _translate("form_asiento", "Septiembre"))
        self.cbx_mes.setItemText(9, _translate("form_asiento", "Octubre"))
        self.cbx_mes.setItemText(10, _translate("form_asiento", "Nombiembre"))
        self.cbx_mes.setItemText(11, _translate("form_asiento", "Diciembre"))
        self.label_5.setText(_translate("form_asiento", "Fecha:"))
        self.dte_fecha.setDisplayFormat(_translate("form_asiento", "dd/MM/yyyy"))
        self.label_2.setText(_translate("form_asiento", "Descripción:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("form_asiento", "Asiento"))
        self.btn_guardar.setText(_translate("form_asiento", "Guardar"))

