# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_libro_iva_ventas.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_form_libro_iva_ventas(object):
    def setupUi(self, form_libro_iva_ventas):
        form_libro_iva_ventas.setObjectName("form_libro_iva_ventas")
        form_libro_iva_ventas.resize(800, 479)
        form_libro_iva_ventas.setMinimumSize(QtCore.QSize(800, 0))
        form_libro_iva_ventas.setMaximumSize(QtCore.QSize(800, 16777215))
        form_libro_iva_ventas.setStyleSheet("font: 10pt \"Liberation Sans\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(156, 156, 156);\n"
"selection-background-color: rgb(164, 190, 221);\n"
"selection-color: rgb(0, 0, 0);")
        self.gridLayout_2 = QtWidgets.QGridLayout(form_libro_iva_ventas)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_15 = QtWidgets.QLabel(form_libro_iva_ventas)
        self.label_15.setMinimumSize(QtCore.QSize(75, 0))
        self.label_15.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_5.addWidget(self.label_15)
        self.lne_cuit = QtWidgets.QLineEdit(form_libro_iva_ventas)
        self.lne_cuit.setMinimumSize(QtCore.QSize(110, 25))
        self.lne_cuit.setMaximumSize(QtCore.QSize(110, 25))
        self.lne_cuit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lne_cuit.setText("")
        self.lne_cuit.setObjectName("lne_cuit")
        self.horizontalLayout_5.addWidget(self.lne_cuit)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_16 = QtWidgets.QLabel(form_libro_iva_ventas)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_6.addWidget(self.label_16)
        self.lne_razon_social = QtWidgets.QLineEdit(form_libro_iva_ventas)
        self.lne_razon_social.setMinimumSize(QtCore.QSize(350, 25))
        self.lne_razon_social.setMaximumSize(QtCore.QSize(350, 25))
        self.lne_razon_social.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lne_razon_social.setObjectName("lne_razon_social")
        self.horizontalLayout_6.addWidget(self.lne_razon_social)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.line = QtWidgets.QFrame(form_libro_iva_ventas)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_7.addWidget(self.line)
        self.btn_buscar = QtWidgets.QPushButton(form_libro_iva_ventas)
        self.btn_buscar.setMinimumSize(QtCore.QSize(75, 50))
        self.btn_buscar.setMaximumSize(QtCore.QSize(75, 50))
        self.btn_buscar.setStyleSheet("background-color: rgb(119, 149, 177);")
        self.btn_buscar.setObjectName("btn_buscar")
        self.horizontalLayout_7.addWidget(self.btn_buscar)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(form_libro_iva_ventas)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(form_libro_iva_ventas)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.cbx_ejercicio = QtWidgets.QComboBox(form_libro_iva_ventas)
        self.cbx_ejercicio.setMinimumSize(QtCore.QSize(125, 25))
        self.cbx_ejercicio.setMaximumSize(QtCore.QSize(125, 25))
        self.cbx_ejercicio.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cbx_ejercicio.setObjectName("cbx_ejercicio")
        self.horizontalLayout.addWidget(self.cbx_ejercicio)
        self.btn_buscar_compra = QtWidgets.QPushButton(form_libro_iva_ventas)
        self.btn_buscar_compra.setMinimumSize(QtCore.QSize(75, 25))
        self.btn_buscar_compra.setMaximumSize(QtCore.QSize(50, 25))
        self.btn_buscar_compra.setStyleSheet("background-color: rgb(119, 149, 177);")
        self.btn_buscar_compra.setObjectName("btn_buscar_compra")
        self.horizontalLayout.addWidget(self.btn_buscar_compra)
        self.label_6 = QtWidgets.QLabel(form_libro_iva_ventas)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.cbx_mes = QtWidgets.QComboBox(form_libro_iva_ventas)
        self.cbx_mes.setMinimumSize(QtCore.QSize(100, 25))
        self.cbx_mes.setMaximumSize(QtCore.QSize(100, 25))
        self.cbx_mes.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cbx_mes.setObjectName("cbx_mes")
        self.cbx_mes.addItem("")
        self.cbx_mes.addItem("")
        self.cbx_mes.addItem("")
        self.cbx_mes.addItem("")
        self.cbx_mes.addItem("")
        self.cbx_mes.addItem("")
        self.cbx_mes.addItem("")
        self.cbx_mes.addItem("")
        self.cbx_mes.addItem("")
        self.cbx_mes.addItem("")
        self.cbx_mes.addItem("")
        self.cbx_mes.addItem("")
        self.horizontalLayout.addWidget(self.cbx_mes)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(form_libro_iva_ventas)
        self.tabWidget.setStyleSheet("QTabWidget{\n"
"background-color: rgb(123, 121, 143);\n"
"}\n"
"QLineEdit {\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"}\n"
"QComboBox{\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.tw_ventas = QtWidgets.QTableWidget(self.tab)
        self.tw_ventas.setStyleSheet("font: 9pt \"Liberation Sans\";")
        self.tw_ventas.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tw_ventas.setObjectName("tw_ventas")
        self.tw_ventas.setColumnCount(17)
        self.tw_ventas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(164, 192, 217))
        self.tw_ventas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(164, 192, 217))
        self.tw_ventas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(164, 192, 217))
        self.tw_ventas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(164, 192, 217))
        self.tw_ventas.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(164, 192, 217))
        self.tw_ventas.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(164, 192, 217))
        self.tw_ventas.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(164, 192, 217))
        self.tw_ventas.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(164, 192, 217))
        self.tw_ventas.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(164, 192, 217))
        self.tw_ventas.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(164, 192, 217))
        self.tw_ventas.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(164, 192, 217))
        self.tw_ventas.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(164, 192, 217))
        self.tw_ventas.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(164, 192, 217))
        self.tw_ventas.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(164, 192, 217))
        self.tw_ventas.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(164, 192, 217))
        self.tw_ventas.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(164, 192, 217))
        self.tw_ventas.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(164, 192, 217))
        self.tw_ventas.setHorizontalHeaderItem(16, item)
        self.tw_ventas.horizontalHeader().setDefaultSectionSize(200)
        self.gridLayout.addWidget(self.tw_ventas, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lne_resultado_uno = QtWidgets.QLineEdit(self.tab)
        self.lne_resultado_uno.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_resultado_uno.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_resultado_uno.setObjectName("lne_resultado_uno")
        self.horizontalLayout_4.addWidget(self.lne_resultado_uno)
        self.lne_resultado_dos = QtWidgets.QLineEdit(self.tab)
        self.lne_resultado_dos.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_resultado_dos.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_resultado_dos.setObjectName("lne_resultado_dos")
        self.horizontalLayout_4.addWidget(self.lne_resultado_dos)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.btn_eliminar = QtWidgets.QPushButton(form_libro_iva_ventas)
        self.btn_eliminar.setMinimumSize(QtCore.QSize(75, 25))
        self.btn_eliminar.setMaximumSize(QtCore.QSize(75, 25))
        self.btn_eliminar.setStyleSheet("background-color: rgb(119, 149, 177);")
        self.btn_eliminar.setObjectName("btn_eliminar")
        self.horizontalLayout_2.addWidget(self.btn_eliminar)
        self.btn_modificar = QtWidgets.QPushButton(form_libro_iva_ventas)
        self.btn_modificar.setMinimumSize(QtCore.QSize(75, 25))
        self.btn_modificar.setMaximumSize(QtCore.QSize(75, 25))
        self.btn_modificar.setStyleSheet("background-color: rgb(119, 149, 177);")
        self.btn_modificar.setObjectName("btn_modificar")
        self.horizontalLayout_2.addWidget(self.btn_modificar)
        self.btn_nuevo = QtWidgets.QPushButton(form_libro_iva_ventas)
        self.btn_nuevo.setMinimumSize(QtCore.QSize(75, 25))
        self.btn_nuevo.setMaximumSize(QtCore.QSize(75, 25))
        self.btn_nuevo.setStyleSheet("background-color: rgb(119, 149, 177);")
        self.btn_nuevo.setObjectName("btn_nuevo")
        self.horizontalLayout_2.addWidget(self.btn_nuevo, 0, QtCore.Qt.AlignRight)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)

        self.retranslateUi(form_libro_iva_ventas)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(form_libro_iva_ventas)
        form_libro_iva_ventas.setTabOrder(self.lne_cuit, self.lne_razon_social)
        form_libro_iva_ventas.setTabOrder(self.lne_razon_social, self.btn_buscar)
        form_libro_iva_ventas.setTabOrder(self.btn_buscar, self.tabWidget)
        form_libro_iva_ventas.setTabOrder(self.tabWidget, self.cbx_ejercicio)
        form_libro_iva_ventas.setTabOrder(self.cbx_ejercicio, self.cbx_mes)
        form_libro_iva_ventas.setTabOrder(self.cbx_mes, self.tw_ventas)
        form_libro_iva_ventas.setTabOrder(self.tw_ventas, self.lne_resultado_uno)
        form_libro_iva_ventas.setTabOrder(self.lne_resultado_uno, self.lne_resultado_dos)

    def retranslateUi(self, form_libro_iva_ventas):
        _translate = QtCore.QCoreApplication.translate
        form_libro_iva_ventas.setWindowTitle(_translate("form_libro_iva_ventas", "Libro IVA Ventas"))
        self.label_15.setText(_translate("form_libro_iva_ventas", "CUIT / CUIL: "))
        self.label_16.setText(_translate("form_libro_iva_ventas", "Razón Social: "))
        self.btn_buscar.setText(_translate("form_libro_iva_ventas", "Buscar"))
        self.label_5.setText(_translate("form_libro_iva_ventas", "Ejercicio:"))
        self.btn_buscar_compra.setText(_translate("form_libro_iva_ventas", "Buscar"))
        self.label_6.setText(_translate("form_libro_iva_ventas", "Mes: "))
        self.cbx_mes.setItemText(0, _translate("form_libro_iva_ventas", "Enero"))
        self.cbx_mes.setItemText(1, _translate("form_libro_iva_ventas", "Febrero"))
        self.cbx_mes.setItemText(2, _translate("form_libro_iva_ventas", "Marzo"))
        self.cbx_mes.setItemText(3, _translate("form_libro_iva_ventas", "Abril"))
        self.cbx_mes.setItemText(4, _translate("form_libro_iva_ventas", "Mayo"))
        self.cbx_mes.setItemText(5, _translate("form_libro_iva_ventas", "Junio"))
        self.cbx_mes.setItemText(6, _translate("form_libro_iva_ventas", "Julio"))
        self.cbx_mes.setItemText(7, _translate("form_libro_iva_ventas", "Agosto"))
        self.cbx_mes.setItemText(8, _translate("form_libro_iva_ventas", "Septiembre"))
        self.cbx_mes.setItemText(9, _translate("form_libro_iva_ventas", "Octubre"))
        self.cbx_mes.setItemText(10, _translate("form_libro_iva_ventas", "Noviembre"))
        self.cbx_mes.setItemText(11, _translate("form_libro_iva_ventas", "Diciembre"))
        item = self.tw_ventas.horizontalHeaderItem(0)
        item.setText(_translate("form_libro_iva_ventas", "Fecha"))
        item = self.tw_ventas.horizontalHeaderItem(1)
        item.setText(_translate("form_libro_iva_ventas", "N° Comprobante"))
        item = self.tw_ventas.horizontalHeaderItem(2)
        item.setText(_translate("form_libro_iva_ventas", "Clientes"))
        item = self.tw_ventas.horizontalHeaderItem(3)
        item.setText(_translate("form_libro_iva_ventas", "Ref."))
        item = self.tw_ventas.horizontalHeaderItem(4)
        item.setText(_translate("form_libro_iva_ventas", "Proveedor"))
        item = self.tw_ventas.horizontalHeaderItem(5)
        item.setText(_translate("form_libro_iva_ventas", "Tipo"))
        item = self.tw_ventas.horizontalHeaderItem(6)
        item.setText(_translate("form_libro_iva_ventas", "CUIT"))
        item = self.tw_ventas.horizontalHeaderItem(7)
        item.setText(_translate("form_libro_iva_ventas", "10.5%"))
        item = self.tw_ventas.horizontalHeaderItem(8)
        item.setText(_translate("form_libro_iva_ventas", "21%"))
        item = self.tw_ventas.horizontalHeaderItem(9)
        item.setText(_translate("form_libro_iva_ventas", "27%"))
        item = self.tw_ventas.horizontalHeaderItem(10)
        item.setText(_translate("form_libro_iva_ventas", "IVA"))
        item = self.tw_ventas.horizontalHeaderItem(11)
        item.setText(_translate("form_libro_iva_ventas", "TOTAL"))
        item = self.tw_ventas.horizontalHeaderItem(12)
        item.setText(_translate("form_libro_iva_ventas", "RET. IVA"))
        item = self.tw_ventas.horizontalHeaderItem(13)
        item.setText(_translate("form_libro_iva_ventas", "RET GANANCIAS"))
        item = self.tw_ventas.horizontalHeaderItem(14)
        item.setText(_translate("form_libro_iva_ventas", "RET IIBB"))
        item = self.tw_ventas.horizontalHeaderItem(15)
        item.setText(_translate("form_libro_iva_ventas", "TOTAL LÍQUIDO"))
        item = self.tw_ventas.horizontalHeaderItem(16)
        item.setText(_translate("form_libro_iva_ventas", "ORDEN DE PAGO"))
        self.label_3.setText(_translate("form_libro_iva_ventas", "Resultado: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("form_libro_iva_ventas", "Libro IVA Ventas"))
        self.btn_eliminar.setText(_translate("form_libro_iva_ventas", "Eliminar"))
        self.btn_modificar.setText(_translate("form_libro_iva_ventas", "Actualizar"))
        self.btn_nuevo.setText(_translate("form_libro_iva_ventas", "Nuevo"))

