# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_clientes.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_form_clientes(object):
    def setupUi(self, form_clientes):
        form_clientes.setObjectName("form_clientes")
        form_clientes.resize(732, 512)
        form_clientes.setStyleSheet("color: rgb(3, 3, 3);\n"
"background-color: rgb(44, 43, 58);\n"
"font: 10pt \"Liberation Sans\";\n"
"color: rgb(252, 252, 252);\n"
"selection-background-color: rgb(155, 155, 185);")
        self.gridLayout_2 = QtWidgets.QGridLayout(form_clientes)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_15 = QtWidgets.QLabel(form_clientes)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_2.addWidget(self.label_15)
        self.lne_cuit = QtWidgets.QLineEdit(form_clientes)
        self.lne_cuit.setMinimumSize(QtCore.QSize(110, 0))
        self.lne_cuit.setMaximumSize(QtCore.QSize(110, 16777215))
        self.lne_cuit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lne_cuit.setText("")
        self.lne_cuit.setObjectName("lne_cuit")
        self.verticalLayout_2.addWidget(self.lne_cuit)
        self.horizontalLayout_15.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_16 = QtWidgets.QLabel(form_clientes)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_3.addWidget(self.label_16)
        self.lne_razon_social = QtWidgets.QLineEdit(form_clientes)
        self.lne_razon_social.setMinimumSize(QtCore.QSize(350, 0))
        self.lne_razon_social.setMaximumSize(QtCore.QSize(350, 16777215))
        self.lne_razon_social.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lne_razon_social.setObjectName("lne_razon_social")
        self.verticalLayout_3.addWidget(self.lne_razon_social)
        self.horizontalLayout_15.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem)
        self.btn_buscar = QtWidgets.QPushButton(form_clientes)
        self.btn_buscar.setMinimumSize(QtCore.QSize(0, 25))
        self.btn_buscar.setMaximumSize(QtCore.QSize(16777215, 25))
        self.btn_buscar.setStyleSheet("background-color: rgb(64, 63, 78);")
        self.btn_buscar.setObjectName("btn_buscar")
        self.horizontalLayout_15.addWidget(self.btn_buscar, 0, QtCore.Qt.AlignBottom)
        self.gridLayout_2.addLayout(self.horizontalLayout_15, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(form_clientes)
        self.tabWidget.setStyleSheet("QTabWidget{\n"
"background-color: rgb(123, 121, 143);\n"
"}\n"
"QLineEdit {\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"}\n"
"QComboBox{\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lne_nombre = QtWidgets.QLineEdit(self.tab)
        self.lne_nombre.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_nombre.setObjectName("lne_nombre")
        self.horizontalLayout.addWidget(self.lne_nombre)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lne_apellido = QtWidgets.QLineEdit(self.tab)
        self.lne_apellido.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_apellido.setObjectName("lne_apellido")
        self.horizontalLayout_2.addWidget(self.lne_apellido)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lne_razon_social_nuevo = QtWidgets.QLineEdit(self.tab)
        self.lne_razon_social_nuevo.setMinimumSize(QtCore.QSize(600, 0))
        self.lne_razon_social_nuevo.setMaximumSize(QtCore.QSize(600, 16777215))
        self.lne_razon_social_nuevo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_razon_social_nuevo.setObjectName("lne_razon_social_nuevo")
        self.horizontalLayout_3.addWidget(self.lne_razon_social_nuevo)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lne_cuit_nuevo = QtWidgets.QLineEdit(self.tab)
        self.lne_cuit_nuevo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_cuit_nuevo.setObjectName("lne_cuit_nuevo")
        self.horizontalLayout_4.addWidget(self.lne_cuit_nuevo)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.cbx_iva = QtWidgets.QComboBox(self.tab)
        self.cbx_iva.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cbx_iva.setObjectName("cbx_iva")
        self.cbx_iva.addItem("")
        self.cbx_iva.addItem("")
        self.cbx_iva.addItem("")
        self.cbx_iva.addItem("")
        self.cbx_iva.addItem("")
        self.horizontalLayout_5.addWidget(self.cbx_iva)
        self.gridLayout.addLayout(self.horizontalLayout_5, 2, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.dte_fec_actividad = QtWidgets.QDateEdit(self.tab)
        self.dte_fec_actividad.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dte_fec_actividad.setObjectName("dte_fec_actividad")
        self.horizontalLayout_6.addWidget(self.dte_fec_actividad)
        self.gridLayout.addLayout(self.horizontalLayout_6, 3, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_12.addWidget(self.label_13)
        self.lne_iibb = QtWidgets.QLineEdit(self.tab)
        self.lne_iibb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_iibb.setObjectName("lne_iibb")
        self.horizontalLayout_12.addWidget(self.lne_iibb)
        self.gridLayout.addLayout(self.horizontalLayout_12, 3, 1, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_13.addWidget(self.label_14)
        self.lne_matricula = QtWidgets.QLineEdit(self.tab)
        self.lne_matricula.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_matricula.setObjectName("lne_matricula")
        self.horizontalLayout_13.addWidget(self.lne_matricula)
        self.gridLayout.addLayout(self.horizontalLayout_13, 4, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.lne_actividad = QtWidgets.QLineEdit(self.tab)
        self.lne_actividad.setMinimumSize(QtCore.QSize(0, 25))
        self.lne_actividad.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lne_actividad.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_actividad.setObjectName("lne_actividad")
        self.verticalLayout.addWidget(self.lne_actividad)
        self.gridLayout.addLayout(self.verticalLayout, 5, 0, 1, 2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.lne_domicilio = QtWidgets.QLineEdit(self.tab)
        self.lne_domicilio.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_domicilio.setObjectName("lne_domicilio")
        self.horizontalLayout_7.addWidget(self.lne_domicilio)
        self.gridLayout.addLayout(self.horizontalLayout_7, 6, 0, 1, 2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.lne_telefono = QtWidgets.QLineEdit(self.tab)
        self.lne_telefono.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_telefono.setObjectName("lne_telefono")
        self.horizontalLayout_8.addWidget(self.lne_telefono)
        self.gridLayout.addLayout(self.horizontalLayout_8, 7, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.lne_celular = QtWidgets.QLineEdit(self.tab)
        self.lne_celular.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_celular.setObjectName("lne_celular")
        self.horizontalLayout_9.addWidget(self.lne_celular)
        self.gridLayout.addLayout(self.horizontalLayout_9, 7, 1, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.lne_email = QtWidgets.QLineEdit(self.tab)
        self.lne_email.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_email.setObjectName("lne_email")
        self.horizontalLayout_10.addWidget(self.lne_email)
        self.gridLayout.addLayout(self.horizontalLayout_10, 8, 0, 1, 2)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.lne_contacto = QtWidgets.QLineEdit(self.tab)
        self.lne_contacto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_contacto.setObjectName("lne_contacto")
        self.horizontalLayout_11.addWidget(self.lne_contacto)
        self.gridLayout.addLayout(self.horizontalLayout_11, 9, 0, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem1)
        self.btn_grabar = QtWidgets.QPushButton(form_clientes)
        self.btn_grabar.setObjectName("btn_grabar")
        self.horizontalLayout_14.addWidget(self.btn_grabar)
        self.btn_modificar = QtWidgets.QPushButton(form_clientes)
        self.btn_modificar.setObjectName("btn_modificar")
        self.horizontalLayout_14.addWidget(self.btn_modificar, 0, QtCore.Qt.AlignRight)
        self.btn_eliminar = QtWidgets.QPushButton(form_clientes)
        self.btn_eliminar.setObjectName("btn_eliminar")
        self.horizontalLayout_14.addWidget(self.btn_eliminar, 0, QtCore.Qt.AlignRight)
        self.gridLayout_2.addLayout(self.horizontalLayout_14, 2, 0, 1, 1)

        self.retranslateUi(form_clientes)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(form_clientes)
        form_clientes.setTabOrder(self.lne_cuit, self.lne_razon_social)
        form_clientes.setTabOrder(self.lne_razon_social, self.btn_buscar)
        form_clientes.setTabOrder(self.btn_buscar, self.tabWidget)
        form_clientes.setTabOrder(self.tabWidget, self.lne_nombre)
        form_clientes.setTabOrder(self.lne_nombre, self.lne_apellido)
        form_clientes.setTabOrder(self.lne_apellido, self.lne_razon_social_nuevo)
        form_clientes.setTabOrder(self.lne_razon_social_nuevo, self.lne_cuit_nuevo)
        form_clientes.setTabOrder(self.lne_cuit_nuevo, self.cbx_iva)
        form_clientes.setTabOrder(self.cbx_iva, self.dte_fec_actividad)
        form_clientes.setTabOrder(self.dte_fec_actividad, self.lne_iibb)
        form_clientes.setTabOrder(self.lne_iibb, self.lne_matricula)
        form_clientes.setTabOrder(self.lne_matricula, self.lne_actividad)
        form_clientes.setTabOrder(self.lne_actividad, self.lne_domicilio)
        form_clientes.setTabOrder(self.lne_domicilio, self.lne_telefono)
        form_clientes.setTabOrder(self.lne_telefono, self.lne_celular)
        form_clientes.setTabOrder(self.lne_celular, self.lne_email)
        form_clientes.setTabOrder(self.lne_email, self.lne_contacto)
        form_clientes.setTabOrder(self.lne_contacto, self.btn_grabar)
        form_clientes.setTabOrder(self.btn_grabar, self.btn_modificar)
        form_clientes.setTabOrder(self.btn_modificar, self.btn_eliminar)

    def retranslateUi(self, form_clientes):
        _translate = QtCore.QCoreApplication.translate
        form_clientes.setWindowTitle(_translate("form_clientes", "Cliente / Empresa"))
        self.label_15.setText(_translate("form_clientes", "CUIT / CUIL: "))
        self.label_16.setText(_translate("form_clientes", "Razón Social: "))
        self.btn_buscar.setText(_translate("form_clientes", "Buscar"))
        self.label.setText(_translate("form_clientes", "Nombre :"))
        self.label_2.setText(_translate("form_clientes", "Apellido :"))
        self.label_3.setText(_translate("form_clientes", "Razón Social :"))
        self.label_4.setText(_translate("form_clientes", "CUIT / CUIL :"))
        self.label_5.setText(_translate("form_clientes", "Condición fte. IVA:"))
        self.cbx_iva.setItemText(0, _translate("form_clientes", "Resp. Monotributo"))
        self.cbx_iva.setItemText(1, _translate("form_clientes", "Resp. Inscripto"))
        self.cbx_iva.setItemText(2, _translate("form_clientes", "Exento"))
        self.cbx_iva.setItemText(3, _translate("form_clientes", "No Alcanzado"))
        self.cbx_iva.setItemText(4, _translate("form_clientes", "Consumidor Final"))
        self.label_6.setText(_translate("form_clientes", "Inicio de Actividades: "))
        self.dte_fec_actividad.setDisplayFormat(_translate("form_clientes", "dd/MM/yyyy"))
        self.label_13.setText(_translate("form_clientes", "N° IIBB: "))
        self.label_14.setText(_translate("form_clientes", "N° Matrícula :"))
        self.label_7.setText(_translate("form_clientes", "Descripción de la Actividad: "))
        self.label_8.setText(_translate("form_clientes", "Domicilio:"))
        self.label_9.setText(_translate("form_clientes", "Teléfono: "))
        self.label_10.setText(_translate("form_clientes", "Celular: "))
        self.label_11.setText(_translate("form_clientes", "Email: "))
        self.label_12.setText(_translate("form_clientes", "Nombre de Contacto: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("form_clientes", "ABM Cliente / Empresa"))
        self.btn_grabar.setText(_translate("form_clientes", "Guardar"))
        self.btn_modificar.setText(_translate("form_clientes", "Modificar"))
        self.btn_eliminar.setText(_translate("form_clientes", "Eliminar"))

