# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_libro_diario.ui'
#
# Created: Wed Feb 14 21:25:02 2018
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_form_libro_diario(object):
    def setupUi(self, form_libro_diario):
        form_libro_diario.setObjectName("form_libro_diario")
        form_libro_diario.resize(798, 558)
        form_libro_diario.setStyleSheet("color: rgb(3, 3, 3);\n"
"background-color: rgb(44, 43, 58);\n"
"font: 10pt \"Liberation Sans\";\n"
"color: rgb(252, 252, 252);\n"
"selection-background-color: rgb(155, 155, 185);")
        self.gridLayout = QtWidgets.QGridLayout(form_libro_diario)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_15 = QtWidgets.QLabel(form_libro_diario)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_4.addWidget(self.label_15)
        self.lne_cuit = QtWidgets.QLineEdit(form_libro_diario)
        self.lne_cuit.setMinimumSize(QtCore.QSize(110, 0))
        self.lne_cuit.setMaximumSize(QtCore.QSize(110, 16777215))
        self.lne_cuit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lne_cuit.setText("")
        self.lne_cuit.setObjectName("lne_cuit")
        self.verticalLayout_4.addWidget(self.lne_cuit)
        self.horizontalLayout_15.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_16 = QtWidgets.QLabel(form_libro_diario)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_5.addWidget(self.label_16)
        self.lne_razon_social = QtWidgets.QLineEdit(form_libro_diario)
        self.lne_razon_social.setMinimumSize(QtCore.QSize(350, 0))
        self.lne_razon_social.setMaximumSize(QtCore.QSize(350, 16777215))
        self.lne_razon_social.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lne_razon_social.setObjectName("lne_razon_social")
        self.verticalLayout_5.addWidget(self.lne_razon_social)
        self.horizontalLayout_15.addLayout(self.verticalLayout_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem)
        self.btn_buscar = QtWidgets.QPushButton(form_libro_diario)
        self.btn_buscar.setMinimumSize(QtCore.QSize(0, 25))
        self.btn_buscar.setMaximumSize(QtCore.QSize(16777215, 25))
        self.btn_buscar.setStyleSheet("background-color: rgb(64, 63, 78);")
        self.btn_buscar.setObjectName("btn_buscar")
        self.horizontalLayout_15.addWidget(self.btn_buscar)
        self.gridLayout.addLayout(self.horizontalLayout_15, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(form_libro_diario)
        self.tabWidget.setStyleSheet("QTabWidget{\n"
"background-color: rgb(123, 121, 143);\n"
"}\n"
"QLineEdit {\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"}\n"
"QComboBox{\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cbx_ejercicio = QtWidgets.QComboBox(self.tab)
        self.cbx_ejercicio.setMinimumSize(QtCore.QSize(250, 25))
        self.cbx_ejercicio.setMaximumSize(QtCore.QSize(250, 25))
        self.cbx_ejercicio.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.cbx_ejercicio.setObjectName("cbx_ejercicio")
        self.horizontalLayout.addWidget(self.cbx_ejercicio)
        self.btn_buscar_ejerc = QtWidgets.QPushButton(self.tab)
        self.btn_buscar_ejerc.setMinimumSize(QtCore.QSize(0, 25))
        self.btn_buscar_ejerc.setMaximumSize(QtCore.QSize(16777215, 25))
        self.btn_buscar_ejerc.setObjectName("btn_buscar_ejerc")
        self.horizontalLayout.addWidget(self.btn_buscar_ejerc)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.tw_asientos = QtWidgets.QTableWidget(self.tab)
        self.tw_asientos.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tw_asientos.setObjectName("tw_asientos")
        self.tw_asientos.setColumnCount(2)
        self.tw_asientos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_asientos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_asientos.setHorizontalHeaderItem(1, item)
        self.tw_asientos.horizontalHeader().setDefaultSectionSize(400)
        self.verticalLayout_2.addWidget(self.tw_asientos)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.btn_nuevo = QtWidgets.QPushButton(self.tab)
        self.btn_nuevo.setStyleSheet("background-color: rgb(64, 63, 78);")
        self.btn_nuevo.setObjectName("btn_nuevo")
        self.horizontalLayout_3.addWidget(self.btn_nuevo)
        self.btn_modificar = QtWidgets.QPushButton(self.tab)
        self.btn_modificar.setStyleSheet("background-color: rgb(64, 63, 78);")
        self.btn_modificar.setObjectName("btn_modificar")
        self.horizontalLayout_3.addWidget(self.btn_modificar)
        self.btn_eliminar = QtWidgets.QPushButton(self.tab)
        self.btn_eliminar.setStyleSheet("background-color: rgb(64, 63, 78);")
        self.btn_eliminar.setObjectName("btn_eliminar")
        self.horizontalLayout_3.addWidget(self.btn_eliminar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.tw_cuentas = QtWidgets.QTableWidget(self.tab)
        self.tw_cuentas.setMinimumSize(QtCore.QSize(0, 150))
        self.tw_cuentas.setMaximumSize(QtCore.QSize(16777215, 150))
        self.tw_cuentas.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tw_cuentas.setObjectName("tw_cuentas")
        self.tw_cuentas.setColumnCount(4)
        self.tw_cuentas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_cuentas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_cuentas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_cuentas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_cuentas.setHorizontalHeaderItem(3, item)
        self.tw_cuentas.horizontalHeader().setDefaultSectionSize(200)
        self.verticalLayout.addWidget(self.tw_cuentas)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btn_nueva_cta = QtWidgets.QPushButton(self.tab)
        self.btn_nueva_cta.setStyleSheet("background-color: rgb(64, 63, 78);")
        self.btn_nueva_cta.setObjectName("btn_nueva_cta")
        self.horizontalLayout_2.addWidget(self.btn_nueva_cta)
        self.btn_modificar_cta = QtWidgets.QPushButton(self.tab)
        self.btn_modificar_cta.setStyleSheet("background-color: rgb(64, 63, 78);")
        self.btn_modificar_cta.setObjectName("btn_modificar_cta")
        self.horizontalLayout_2.addWidget(self.btn_modificar_cta)
        self.btn_eliminar_cta = QtWidgets.QPushButton(self.tab)
        self.btn_eliminar_cta.setStyleSheet("background-color: rgb(64, 63, 78);")
        self.btn_eliminar_cta.setObjectName("btn_eliminar_cta")
        self.horizontalLayout_2.addWidget(self.btn_eliminar_cta)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)

        self.retranslateUi(form_libro_diario)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(form_libro_diario)
        form_libro_diario.setTabOrder(self.lne_cuit, self.lne_razon_social)
        form_libro_diario.setTabOrder(self.lne_razon_social, self.btn_buscar)
        form_libro_diario.setTabOrder(self.btn_buscar, self.tabWidget)
        form_libro_diario.setTabOrder(self.tabWidget, self.cbx_ejercicio)
        form_libro_diario.setTabOrder(self.cbx_ejercicio, self.btn_buscar_ejerc)
        form_libro_diario.setTabOrder(self.btn_buscar_ejerc, self.tw_asientos)
        form_libro_diario.setTabOrder(self.tw_asientos, self.btn_nuevo)
        form_libro_diario.setTabOrder(self.btn_nuevo, self.btn_modificar)
        form_libro_diario.setTabOrder(self.btn_modificar, self.btn_eliminar)
        form_libro_diario.setTabOrder(self.btn_eliminar, self.tw_cuentas)
        form_libro_diario.setTabOrder(self.tw_cuentas, self.btn_nueva_cta)
        form_libro_diario.setTabOrder(self.btn_nueva_cta, self.btn_modificar_cta)
        form_libro_diario.setTabOrder(self.btn_modificar_cta, self.btn_eliminar_cta)

    def retranslateUi(self, form_libro_diario):
        _translate = QtCore.QCoreApplication.translate
        form_libro_diario.setWindowTitle(_translate("form_libro_diario", "Libro Diario"))
        self.label_15.setText(_translate("form_libro_diario", "CUIT / CUIL: "))
        self.label_16.setText(_translate("form_libro_diario", "Razón Social: "))
        self.btn_buscar.setText(_translate("form_libro_diario", "Buscar"))
        self.label.setText(_translate("form_libro_diario", "Ejercicio:"))
        self.btn_buscar_ejerc.setText(_translate("form_libro_diario", "Buscar"))
        self.label_3.setText(_translate("form_libro_diario", "Asientos: "))
        item = self.tw_asientos.horizontalHeaderItem(0)
        item.setText(_translate("form_libro_diario", "Fecha"))
        item = self.tw_asientos.horizontalHeaderItem(1)
        item.setText(_translate("form_libro_diario", "Descripción"))
        self.btn_nuevo.setText(_translate("form_libro_diario", "Agregar"))
        self.btn_modificar.setText(_translate("form_libro_diario", "Modificar"))
        self.btn_eliminar.setText(_translate("form_libro_diario", "Borrar"))
        self.label_4.setText(_translate("form_libro_diario", "Cuentas:"))
        item = self.tw_cuentas.horizontalHeaderItem(0)
        item.setText(_translate("form_libro_diario", "Código"))
        item = self.tw_cuentas.horizontalHeaderItem(1)
        item.setText(_translate("form_libro_diario", "Descripción"))
        item = self.tw_cuentas.horizontalHeaderItem(2)
        item.setText(_translate("form_libro_diario", "Neto"))
        item = self.tw_cuentas.horizontalHeaderItem(3)
        item.setText(_translate("form_libro_diario", "Haber"))
        self.btn_nueva_cta.setText(_translate("form_libro_diario", "Agregar"))
        self.btn_modificar_cta.setText(_translate("form_libro_diario", "Modificar"))
        self.btn_eliminar_cta.setText(_translate("form_libro_diario", "Borrar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("form_libro_diario", "Libro Diario "))

