# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_balancear_asiento.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_form_balancear_asiento(object):
    def setupUi(self, form_balancear_asiento):
        form_balancear_asiento.setObjectName("form_balancear_asiento")
        form_balancear_asiento.resize(553, 350)
        form_balancear_asiento.setMinimumSize(QtCore.QSize(100, 350))
        form_balancear_asiento.setMaximumSize(QtCore.QSize(1000, 350))
        form_balancear_asiento.setStyleSheet("font: 10pt \"Liberation Sans\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(156, 156, 156);\n"
"selection-background-color: rgb(164, 190, 221);\n"
"selection-color: rgb(0, 0, 0);")
        self.gridLayout = QtWidgets.QGridLayout(form_balancear_asiento)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(form_balancear_asiento)
        self.label.setMinimumSize(QtCore.QSize(50, 25))
        self.label.setMaximumSize(QtCore.QSize(50, 25))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lne_cuit = QtWidgets.QLineEdit(form_balancear_asiento)
        self.lne_cuit.setMinimumSize(QtCore.QSize(250, 25))
        self.lne_cuit.setMaximumSize(QtCore.QSize(250, 25))
        self.lne_cuit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_cuit.setObjectName("lne_cuit")
        self.horizontalLayout.addWidget(self.lne_cuit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(form_balancear_asiento)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lne_razon_social = QtWidgets.QLineEdit(form_balancear_asiento)
        self.lne_razon_social.setMinimumSize(QtCore.QSize(350, 25))
        self.lne_razon_social.setMaximumSize(QtCore.QSize(350, 25))
        self.lne_razon_social.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_razon_social.setObjectName("lne_razon_social")
        self.horizontalLayout_2.addWidget(self.lne_razon_social)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.btn_buscar = QtWidgets.QPushButton(form_balancear_asiento)
        self.btn_buscar.setStyleSheet("background-color: rgb(119, 149, 177);")
        self.btn_buscar.setObjectName("btn_buscar")
        self.horizontalLayout_3.addWidget(self.btn_buscar)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(form_balancear_asiento)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(form_balancear_asiento)
        self.label_3.setMinimumSize(QtCore.QSize(100, 25))
        self.label_3.setMaximumSize(QtCore.QSize(100, 25))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.cbx_ejercicio = QtWidgets.QComboBox(form_balancear_asiento)
        self.cbx_ejercicio.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cbx_ejercicio.setObjectName("cbx_ejercicio")
        self.horizontalLayout_4.addWidget(self.cbx_ejercicio)
        self.btn_calcular_asientos = QtWidgets.QPushButton(form_balancear_asiento)
        self.btn_calcular_asientos.setStyleSheet("background-color: rgb(119, 149, 177);")
        self.btn_calcular_asientos.setObjectName("btn_calcular_asientos")
        self.horizontalLayout_4.addWidget(self.btn_calcular_asientos)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(form_balancear_asiento)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 3, 0, 1, 1)
        self.tb_asientos = QtWidgets.QTableWidget(form_balancear_asiento)
        self.tb_asientos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tb_asientos.setObjectName("tb_asientos")
        self.tb_asientos.setColumnCount(4)
        self.tb_asientos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tb_asientos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_asientos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_asientos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_asientos.setHorizontalHeaderItem(3, item)
        self.tb_asientos.horizontalHeader().setDefaultSectionSize(150)
        self.tb_asientos.horizontalHeader().setMinimumSectionSize(20)
        self.gridLayout.addWidget(self.tb_asientos, 4, 0, 1, 1)

        self.retranslateUi(form_balancear_asiento)
        QtCore.QMetaObject.connectSlotsByName(form_balancear_asiento)

    def retranslateUi(self, form_balancear_asiento):
        _translate = QtCore.QCoreApplication.translate
        form_balancear_asiento.setWindowTitle(_translate("form_balancear_asiento", "balancear asiento"))
        self.label.setText(_translate("form_balancear_asiento", "CUIT:"))
        self.label_2.setText(_translate("form_balancear_asiento", "Razon Social:"))
        self.btn_buscar.setText(_translate("form_balancear_asiento", "Buscar"))
        self.label_3.setText(_translate("form_balancear_asiento", "Ejercicio :"))
        self.btn_calcular_asientos.setText(_translate("form_balancear_asiento", "Calcular Asientos"))
        item = self.tb_asientos.horizontalHeaderItem(0)
        item.setText(_translate("form_balancear_asiento", "FECHA"))
        item = self.tb_asientos.horizontalHeaderItem(1)
        item.setText(_translate("form_balancear_asiento", "ASIENTO"))
        item = self.tb_asientos.horizontalHeaderItem(2)
        item.setText(_translate("form_balancear_asiento", "DEBE"))
        item = self.tb_asientos.horizontalHeaderItem(3)
        item.setText(_translate("form_balancear_asiento", "HABER"))

