# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_inflacion.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_form_inflacion(object):
    def setupUi(self, form_inflacion):
        form_inflacion.setObjectName("form_inflacion")
        form_inflacion.resize(344, 441)
        form_inflacion.setStyleSheet("font: 10pt \"Liberation Sans\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(156, 156, 156);\n"
"selection-background-color: rgb(164, 190, 221);\n"
"selection-color: rgb(0, 0, 0);")
        self.gridLayout = QtWidgets.QGridLayout(form_inflacion)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 6, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.cbx_anio = QtWidgets.QComboBox(form_inflacion)
        self.cbx_anio.setMinimumSize(QtCore.QSize(75, 25))
        self.cbx_anio.setMaximumSize(QtCore.QSize(75, 25))
        self.cbx_anio.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cbx_anio.setObjectName("cbx_anio")
        self.cbx_anio.addItem("")
        self.cbx_anio.addItem("")
        self.cbx_anio.addItem("")
        self.cbx_anio.addItem("")
        self.horizontalLayout.addWidget(self.cbx_anio)
        self.btn_buscar = QtWidgets.QPushButton(form_inflacion)
        self.btn_buscar.setStyleSheet("background-color: rgb(119, 149, 177);")
        self.btn_buscar.setObjectName("btn_buscar")
        self.horizontalLayout.addWidget(self.btn_buscar)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 7, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(form_inflacion)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lne_enero = QtWidgets.QLineEdit(form_inflacion)
        self.lne_enero.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_enero.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_enero.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_enero.setObjectName("lne_enero")
        self.horizontalLayout_2.addWidget(self.lne_enero)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(form_inflacion)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lne_febrero = QtWidgets.QLineEdit(form_inflacion)
        self.lne_febrero.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_febrero.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_febrero.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_febrero.setObjectName("lne_febrero")
        self.horizontalLayout_3.addWidget(self.lne_febrero)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(form_inflacion)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lne_marzo = QtWidgets.QLineEdit(form_inflacion)
        self.lne_marzo.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_marzo.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_marzo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_marzo.setObjectName("lne_marzo")
        self.horizontalLayout_4.addWidget(self.lne_marzo)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(form_inflacion)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.lne_abril = QtWidgets.QLineEdit(form_inflacion)
        self.lne_abril.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_abril.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_abril.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_abril.setObjectName("lne_abril")
        self.horizontalLayout_5.addWidget(self.lne_abril)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(form_inflacion)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.lne_mayo = QtWidgets.QLineEdit(form_inflacion)
        self.lne_mayo.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_mayo.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_mayo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_mayo.setObjectName("lne_mayo")
        self.horizontalLayout_6.addWidget(self.lne_mayo)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(form_inflacion)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.lne_junio = QtWidgets.QLineEdit(form_inflacion)
        self.lne_junio.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_junio.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_junio.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_junio.setObjectName("lne_junio")
        self.horizontalLayout_7.addWidget(self.lne_junio)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(form_inflacion)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.lne_julio = QtWidgets.QLineEdit(form_inflacion)
        self.lne_julio.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_julio.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_julio.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_julio.setObjectName("lne_julio")
        self.horizontalLayout_8.addWidget(self.lne_julio)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(form_inflacion)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.lne_agosto = QtWidgets.QLineEdit(form_inflacion)
        self.lne_agosto.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_agosto.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_agosto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_agosto.setObjectName("lne_agosto")
        self.horizontalLayout_9.addWidget(self.lne_agosto)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtWidgets.QLabel(form_inflacion)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.lne_septiembre = QtWidgets.QLineEdit(form_inflacion)
        self.lne_septiembre.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_septiembre.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_septiembre.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_septiembre.setObjectName("lne_septiembre")
        self.horizontalLayout_10.addWidget(self.lne_septiembre)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_10 = QtWidgets.QLabel(form_inflacion)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_11.addWidget(self.label_10)
        self.lne_octubre = QtWidgets.QLineEdit(form_inflacion)
        self.lne_octubre.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_octubre.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_octubre.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_octubre.setObjectName("lne_octubre")
        self.horizontalLayout_11.addWidget(self.lne_octubre)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_11 = QtWidgets.QLabel(form_inflacion)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_12.addWidget(self.label_11)
        self.lne_noviembre = QtWidgets.QLineEdit(form_inflacion)
        self.lne_noviembre.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_noviembre.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_noviembre.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_noviembre.setObjectName("lne_noviembre")
        self.horizontalLayout_12.addWidget(self.lne_noviembre)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_12 = QtWidgets.QLabel(form_inflacion)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_13.addWidget(self.label_12)
        self.lne_diciembre = QtWidgets.QLineEdit(form_inflacion)
        self.lne_diciembre.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_diciembre.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_diciembre.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lne_diciembre.setObjectName("lne_diciembre")
        self.horizontalLayout_13.addWidget(self.lne_diciembre)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.gridLayout.addLayout(self.verticalLayout, 1, 7, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 1, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 0, 3, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 1, 10, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 0, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 1, 5, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem11, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem12)
        self.btn_guardar = QtWidgets.QPushButton(form_inflacion)
        self.btn_guardar.setStyleSheet("background-color: rgb(119, 149, 177);")
        self.btn_guardar.setObjectName("btn_guardar")
        self.verticalLayout_2.addWidget(self.btn_guardar)
        self.btn_actualizar = QtWidgets.QPushButton(form_inflacion)
        self.btn_actualizar.setStyleSheet("background-color: rgb(119, 149, 177);")
        self.btn_actualizar.setObjectName("btn_actualizar")
        self.verticalLayout_2.addWidget(self.btn_actualizar)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem13)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 8, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem14, 1, 3, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem15, 1, 9, 1, 1)

        self.retranslateUi(form_inflacion)
        QtCore.QMetaObject.connectSlotsByName(form_inflacion)

    def retranslateUi(self, form_inflacion):
        _translate = QtCore.QCoreApplication.translate
        form_inflacion.setWindowTitle(_translate("form_inflacion", "Form"))
        self.cbx_anio.setItemText(0, _translate("form_inflacion", "2017"))
        self.cbx_anio.setItemText(1, _translate("form_inflacion", "2018"))
        self.cbx_anio.setItemText(2, _translate("form_inflacion", "2019"))
        self.cbx_anio.setItemText(3, _translate("form_inflacion", "2020"))
        self.btn_buscar.setText(_translate("form_inflacion", "buscar"))
        self.label.setText(_translate("form_inflacion", "Enero"))
        self.label_2.setText(_translate("form_inflacion", "Febrero"))
        self.label_3.setText(_translate("form_inflacion", "Marzo"))
        self.label_4.setText(_translate("form_inflacion", "Abril"))
        self.label_5.setText(_translate("form_inflacion", "Mayo"))
        self.label_6.setText(_translate("form_inflacion", "Junio"))
        self.label_7.setText(_translate("form_inflacion", "Julio"))
        self.label_8.setText(_translate("form_inflacion", "Agosto"))
        self.label_9.setText(_translate("form_inflacion", "Septiembre"))
        self.label_10.setText(_translate("form_inflacion", "Octubre"))
        self.label_11.setText(_translate("form_inflacion", "Noviembre"))
        self.label_12.setText(_translate("form_inflacion", "Diciembre"))
        self.btn_guardar.setText(_translate("form_inflacion", "guardar"))
        self.btn_actualizar.setText(_translate("form_inflacion", "actualizar"))

