# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_plan_cuentas.ui'
#
# Created: Sun Mar 24 16:52:51 2019
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_form_plan_cuentas(object):
    def setupUi(self, form_plan_cuentas):
        form_plan_cuentas.setObjectName("form_plan_cuentas")
        form_plan_cuentas.resize(700, 500)
        form_plan_cuentas.setMinimumSize(QtCore.QSize(700, 500))
        form_plan_cuentas.setMaximumSize(QtCore.QSize(700, 500))
        form_plan_cuentas.setStyleSheet("font: 10pt \"Liberation Sans\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(156, 156, 156);\n"
"selection-background-color: rgb(164, 190, 221);\n"
"selection-color: rgb(0, 0, 0);")
        self.gridLayout_2 = QtWidgets.QGridLayout(form_plan_cuentas)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(form_plan_cuentas)
        self.tabWidget.setStyleSheet("QTabWidget{\n"
"background-color: rgb(123, 121, 143);\n"
"}\n"
"QLineEdit {\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"}\n"
"QComboBox{\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.tw_plan_ctas = QtWidgets.QTableWidget(self.tab)
        self.tw_plan_ctas.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tw_plan_ctas.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tw_plan_ctas.setObjectName("tw_plan_ctas")
        self.tw_plan_ctas.setColumnCount(4)
        self.tw_plan_ctas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setBackground(QtGui.QColor(148, 174, 196))
        self.tw_plan_ctas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setBackground(QtGui.QColor(156, 183, 206))
        self.tw_plan_ctas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_plan_ctas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setBackground(QtGui.QColor(156, 183, 206))
        self.tw_plan_ctas.setHorizontalHeaderItem(3, item)
        self.tw_plan_ctas.horizontalHeader().setCascadingSectionResizes(True)
        self.tw_plan_ctas.horizontalHeader().setDefaultSectionSize(290)
        self.tw_plan_ctas.horizontalHeader().setStretchLastSection(False)
        self.tw_plan_ctas.verticalHeader().setCascadingSectionResizes(False)
        self.tw_plan_ctas.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tw_plan_ctas, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 2, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_3 = QtWidgets.QLabel(form_plan_cuentas)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(form_plan_cuentas)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lne_codigo = QtWidgets.QLineEdit(form_plan_cuentas)
        self.lne_codigo.setMinimumSize(QtCore.QSize(100, 25))
        self.lne_codigo.setMaximumSize(QtCore.QSize(100, 25))
        self.lne_codigo.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.lne_codigo.setObjectName("lne_codigo")
        self.horizontalLayout.addWidget(self.lne_codigo)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem11)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem12)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem13)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem14)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem15)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem16)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem17)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem18)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem19)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem20)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem21)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem22)
        self.gridLayout_6.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(form_plan_cuentas)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lne_descripcion = QtWidgets.QLineEdit(form_plan_cuentas)
        self.lne_descripcion.setMinimumSize(QtCore.QSize(400, 25))
        self.lne_descripcion.setMaximumSize(QtCore.QSize(400, 25))
        self.lne_descripcion.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lne_descripcion.setText("")
        self.lne_descripcion.setObjectName("lne_descripcion")
        self.horizontalLayout_2.addWidget(self.lne_descripcion)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem23)
        self.gridLayout_6.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_6, 4, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(form_plan_cuentas)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(form_plan_cuentas)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 5, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_15 = QtWidgets.QLabel(form_plan_cuentas)
        self.label_15.setMinimumSize(QtCore.QSize(75, 25))
        self.label_15.setMaximumSize(QtCore.QSize(75, 25))
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 0, 0, 1, 1)
        self.lne_cuit = QtWidgets.QLineEdit(form_plan_cuentas)
        self.lne_cuit.setMinimumSize(QtCore.QSize(110, 0))
        self.lne_cuit.setMaximumSize(QtCore.QSize(110, 16777215))
        self.lne_cuit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lne_cuit.setText("")
        self.lne_cuit.setObjectName("lne_cuit")
        self.gridLayout_5.addWidget(self.lne_cuit, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_16 = QtWidgets.QLabel(form_plan_cuentas)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_5.addWidget(self.label_16)
        self.lne_razon_social = QtWidgets.QLineEdit(form_plan_cuentas)
        self.lne_razon_social.setMinimumSize(QtCore.QSize(250, 0))
        self.lne_razon_social.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lne_razon_social.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lne_razon_social.setObjectName("lne_razon_social")
        self.horizontalLayout_5.addWidget(self.lne_razon_social)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 0, 1, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem24, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.btn_buscar = QtWidgets.QPushButton(form_plan_cuentas)
        self.btn_buscar.setMinimumSize(QtCore.QSize(75, 50))
        self.btn_buscar.setMaximumSize(QtCore.QSize(75, 50))
        self.btn_buscar.setStyleSheet("background-color: rgb(119, 149, 177);")
        self.btn_buscar.setObjectName("btn_buscar")
        self.gridLayout_3.addWidget(self.btn_buscar, 0, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(form_plan_cuentas)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(form_plan_cuentas)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem25)
        self.btn_agregar = QtWidgets.QPushButton(form_plan_cuentas)
        self.btn_agregar.setStyleSheet("background-color: rgb(119, 149, 177);")
        self.btn_agregar.setObjectName("btn_agregar")
        self.horizontalLayout_3.addWidget(self.btn_agregar)
        self.btn_modificar = QtWidgets.QPushButton(form_plan_cuentas)
        self.btn_modificar.setStyleSheet("background-color: rgb(119, 149, 177);")
        self.btn_modificar.setObjectName("btn_modificar")
        self.horizontalLayout_3.addWidget(self.btn_modificar)
        self.btn_eliminar = QtWidgets.QPushButton(form_plan_cuentas)
        self.btn_eliminar.setStyleSheet("background-color: rgb(119, 149, 177);")
        self.btn_eliminar.setObjectName("btn_eliminar")
        self.horizontalLayout_3.addWidget(self.btn_eliminar)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 9, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(form_plan_cuentas)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 8, 0, 1, 1)
        self.cbx_inflacion = QtWidgets.QComboBox(form_plan_cuentas)
        self.cbx_inflacion.setObjectName("cbx_inflacion")
        self.cbx_inflacion.addItem("")
        self.cbx_inflacion.addItem("")
        self.gridLayout_2.addWidget(self.cbx_inflacion, 6, 0, 1, 1)

        self.retranslateUi(form_plan_cuentas)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(form_plan_cuentas)
        form_plan_cuentas.setTabOrder(self.lne_cuit, self.lne_razon_social)
        form_plan_cuentas.setTabOrder(self.lne_razon_social, self.btn_buscar)
        form_plan_cuentas.setTabOrder(self.btn_buscar, self.tabWidget)
        form_plan_cuentas.setTabOrder(self.tabWidget, self.tw_plan_ctas)
        form_plan_cuentas.setTabOrder(self.tw_plan_ctas, self.lne_codigo)
        form_plan_cuentas.setTabOrder(self.lne_codigo, self.lne_descripcion)
        form_plan_cuentas.setTabOrder(self.lne_descripcion, self.btn_agregar)
        form_plan_cuentas.setTabOrder(self.btn_agregar, self.btn_modificar)
        form_plan_cuentas.setTabOrder(self.btn_modificar, self.btn_eliminar)

    def retranslateUi(self, form_plan_cuentas):
        _translate = QtCore.QCoreApplication.translate
        form_plan_cuentas.setWindowTitle(_translate("form_plan_cuentas", "Plan de Cuentas"))
        item = self.tw_plan_ctas.horizontalHeaderItem(0)
        item.setText(_translate("form_plan_cuentas", "Código"))
        item = self.tw_plan_ctas.horizontalHeaderItem(1)
        item.setText(_translate("form_plan_cuentas", "Descripción"))
        item = self.tw_plan_ctas.horizontalHeaderItem(2)
        item.setText(_translate("form_plan_cuentas", "inflacion"))
        item = self.tw_plan_ctas.horizontalHeaderItem(3)
        item.setText(_translate("form_plan_cuentas", "ID"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("form_plan_cuentas", "Plan de Cuentas "))
        self.label_3.setText(_translate("form_plan_cuentas", "Detalle del Plan:"))
        self.label.setText(_translate("form_plan_cuentas", "Código: "))
        self.label_2.setText(_translate("form_plan_cuentas", "Descripción:"))
        self.label_4.setText(_translate("form_plan_cuentas", "Inflacion:"))
        self.label_15.setText(_translate("form_plan_cuentas", "CUIT / CUIL: "))
        self.label_16.setText(_translate("form_plan_cuentas", "Razón Social: "))
        self.btn_buscar.setText(_translate("form_plan_cuentas", "Buscar"))
        self.btn_agregar.setText(_translate("form_plan_cuentas", "Agregar"))
        self.btn_modificar.setText(_translate("form_plan_cuentas", "Modificar"))
        self.btn_eliminar.setText(_translate("form_plan_cuentas", "Eliminar"))
        self.cbx_inflacion.setItemText(0, _translate("form_plan_cuentas", "False"))
        self.cbx_inflacion.setItemText(1, _translate("form_plan_cuentas", "True"))

