# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sat Mar 23 15:24:30 2019
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(584, 559)
        MainWindow.setMinimumSize(QtCore.QSize(550, 450))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        MainWindow.setStyleSheet("font: 10pt \"Liberation Sans\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(156, 156, 156);\n"
"selection-background-color: rgb(164, 190, 221);\n"
"selection-color: rgb(0, 0, 0);")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_clientes = QtWidgets.QPushButton(self.centralWidget)
        self.btn_clientes.setMinimumSize(QtCore.QSize(61, 55))
        self.btn_clientes.setMaximumSize(QtCore.QSize(61, 55))
        self.btn_clientes.setStyleSheet("background-color: rgb(123, 117, 154);\n"
"background-color: rgb(168, 168, 168);")
        self.btn_clientes.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Íconos/silueta-masculina-de-usuario.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_clientes.setIcon(icon)
        self.btn_clientes.setIconSize(QtCore.QSize(50, 50))
        self.btn_clientes.setObjectName("btn_clientes")
        self.verticalLayout.addWidget(self.btn_clientes)
        self.btn_ejercicios = QtWidgets.QPushButton(self.centralWidget)
        self.btn_ejercicios.setMinimumSize(QtCore.QSize(61, 55))
        self.btn_ejercicios.setMaximumSize(QtCore.QSize(61, 55))
        self.btn_ejercicios.setStyleSheet("background-color: rgb(123, 117, 154);\n"
"background-color: rgb(168, 168, 168);")
        self.btn_ejercicios.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Íconos/calidad-de-la-pagina.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ejercicios.setIcon(icon1)
        self.btn_ejercicios.setIconSize(QtCore.QSize(50, 50))
        self.btn_ejercicios.setObjectName("btn_ejercicios")
        self.verticalLayout.addWidget(self.btn_ejercicios)
        self.btn_libros = QtWidgets.QPushButton(self.centralWidget)
        self.btn_libros.setMinimumSize(QtCore.QSize(61, 55))
        self.btn_libros.setMaximumSize(QtCore.QSize(61, 55))
        self.btn_libros.setStyleSheet("background-color: rgb(123, 117, 154);\n"
"background-color: rgb(168, 168, 168);")
        self.btn_libros.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Íconos/herramientas-de-papel-y-lapiz.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_libros.setIcon(icon2)
        self.btn_libros.setIconSize(QtCore.QSize(50, 50))
        self.btn_libros.setObjectName("btn_libros")
        self.verticalLayout.addWidget(self.btn_libros)
        self.btn_libro_ventas = QtWidgets.QPushButton(self.centralWidget)
        self.btn_libro_ventas.setMinimumSize(QtCore.QSize(61, 55))
        self.btn_libro_ventas.setMaximumSize(QtCore.QSize(61, 55))
        self.btn_libro_ventas.setStyleSheet("")
        self.btn_libro_ventas.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Íconos/casilla-y-boligrafo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_libro_ventas.setIcon(icon3)
        self.btn_libro_ventas.setIconSize(QtCore.QSize(50, 50))
        self.btn_libro_ventas.setObjectName("btn_libro_ventas")
        self.verticalLayout.addWidget(self.btn_libro_ventas)
        self.btn_proveedores = QtWidgets.QPushButton(self.centralWidget)
        self.btn_proveedores.setMinimumSize(QtCore.QSize(61, 55))
        self.btn_proveedores.setMaximumSize(QtCore.QSize(61, 55))
        self.btn_proveedores.setStyleSheet("background-color: rgb(123, 117, 154);\n"
"background-color: rgb(168, 168, 168);")
        self.btn_proveedores.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Íconos/tranvia.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_proveedores.setIcon(icon4)
        self.btn_proveedores.setIconSize(QtCore.QSize(50, 50))
        self.btn_proveedores.setObjectName("btn_proveedores")
        self.verticalLayout.addWidget(self.btn_proveedores)
        self.btn_reporte_diario = QtWidgets.QPushButton(self.centralWidget)
        self.btn_reporte_diario.setMinimumSize(QtCore.QSize(61, 55))
        self.btn_reporte_diario.setMaximumSize(QtCore.QSize(61, 55))
        self.btn_reporte_diario.setStyleSheet("background-color: rgb(123, 117, 154);\n"
"background-color: rgb(168, 168, 168);")
        self.btn_reporte_diario.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Íconos/documento-financiero.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_reporte_diario.setIcon(icon5)
        self.btn_reporte_diario.setIconSize(QtCore.QSize(50, 50))
        self.btn_reporte_diario.setObjectName("btn_reporte_diario")
        self.verticalLayout.addWidget(self.btn_reporte_diario)
        self.btn_reporte_saldos = QtWidgets.QPushButton(self.centralWidget)
        self.btn_reporte_saldos.setMinimumSize(QtCore.QSize(61, 55))
        self.btn_reporte_saldos.setMaximumSize(QtCore.QSize(61, 55))
        self.btn_reporte_saldos.setStyleSheet("background-color: rgb(123, 117, 154);\n"
"background-color: rgb(168, 168, 168);")
        self.btn_reporte_saldos.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Íconos/calculadora.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_reporte_saldos.setIcon(icon6)
        self.btn_reporte_saldos.setIconSize(QtCore.QSize(50, 50))
        self.btn_reporte_saldos.setObjectName("btn_reporte_saldos")
        self.verticalLayout.addWidget(self.btn_reporte_saldos)
        self.btn_reporte_mayor = QtWidgets.QPushButton(self.centralWidget)
        self.btn_reporte_mayor.setMinimumSize(QtCore.QSize(61, 55))
        self.btn_reporte_mayor.setMaximumSize(QtCore.QSize(61, 55))
        self.btn_reporte_mayor.setStyleSheet("background-color: rgb(123, 117, 154);\n"
"background-color: rgb(168, 168, 168);")
        self.btn_reporte_mayor.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Íconos/maquina-de-facturacion-electronica-con-escaner.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_reporte_mayor.setIcon(icon7)
        self.btn_reporte_mayor.setIconSize(QtCore.QSize(50, 50))
        self.btn_reporte_mayor.setObjectName("btn_reporte_mayor")
        self.verticalLayout.addWidget(self.btn_reporte_mayor)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 2, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setMinimumSize(QtCore.QSize(161, 21))
        self.label.setMaximumSize(QtCore.QSize(161, 21))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Íconos/logoslamqt_blanco.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 584, 20))
        self.menuBar.setObjectName("menuBar")
        self.menuCLIENTE = QtWidgets.QMenu(self.menuBar)
        self.menuCLIENTE.setObjectName("menuCLIENTE")
        self.menuASIENTOS = QtWidgets.QMenu(self.menuBar)
        self.menuASIENTOS.setObjectName("menuASIENTOS")
        self.menuCuentas = QtWidgets.QMenu(self.menuASIENTOS)
        self.menuCuentas.setObjectName("menuCuentas")
        self.menuREPORTES = QtWidgets.QMenu(self.menuBar)
        self.menuREPORTES.setObjectName("menuREPORTES")
        self.menuCUENTAS = QtWidgets.QMenu(self.menuBar)
        self.menuCUENTAS.setObjectName("menuCUENTAS")
        self.menuLIBROS = QtWidgets.QMenu(self.menuBar)
        self.menuLIBROS.setObjectName("menuLIBROS")
        self.menuLibro_IVA_Compras = QtWidgets.QMenu(self.menuLIBROS)
        self.menuLibro_IVA_Compras.setObjectName("menuLibro_IVA_Compras")
        self.menuLibro_IVA_Ventas = QtWidgets.QMenu(self.menuLIBROS)
        self.menuLibro_IVA_Ventas.setObjectName("menuLibro_IVA_Ventas")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionEjercicio = QtWidgets.QAction(MainWindow)
        self.actionEjercicio.setObjectName("actionEjercicio")
        self.actionLIBRO_DIARIO = QtWidgets.QAction(MainWindow)
        self.actionLIBRO_DIARIO.setObjectName("actionLIBRO_DIARIO")
        self.actionClientes = QtWidgets.QAction(MainWindow)
        self.actionClientes.setObjectName("actionClientes")
        self.actionNuevo_Ejercicio = QtWidgets.QAction(MainWindow)
        self.actionNuevo_Ejercicio.setObjectName("actionNuevo_Ejercicio")
        self.actionLibro_IVA_Ventas = QtWidgets.QAction(MainWindow)
        self.actionLibro_IVA_Ventas.setObjectName("actionLibro_IVA_Ventas")
        self.actionLibro_IVA_Compras = QtWidgets.QAction(MainWindow)
        self.actionLibro_IVA_Compras.setObjectName("actionLibro_IVA_Compras")
        self.actionLibro_Mayor = QtWidgets.QAction(MainWindow)
        self.actionLibro_Mayor.setObjectName("actionLibro_Mayor")
        self.actionLibro_Diario_General = QtWidgets.QAction(MainWindow)
        self.actionLibro_Diario_General.setObjectName("actionLibro_Diario_General")
        self.actionSumas_y_Saldos = QtWidgets.QAction(MainWindow)
        self.actionSumas_y_Saldos.setObjectName("actionSumas_y_Saldos")
        self.actionAlta_de_proveedores = QtWidgets.QAction(MainWindow)
        self.actionAlta_de_proveedores.setObjectName("actionAlta_de_proveedores")
        self.actionNuevo = QtWidgets.QAction(MainWindow)
        self.actionNuevo.setObjectName("actionNuevo")
        self.actionBuscar_Cuenta = QtWidgets.QAction(MainWindow)
        self.actionBuscar_Cuenta.setObjectName("actionBuscar_Cuenta")
        self.actionPlan_Cuentas = QtWidgets.QAction(MainWindow)
        self.actionPlan_Cuentas.setObjectName("actionPlan_Cuentas")
        self.actionAsiento = QtWidgets.QAction(MainWindow)
        self.actionAsiento.setObjectName("actionAsiento")
        self.actionBuscar = QtWidgets.QAction(MainWindow)
        self.actionBuscar.setObjectName("actionBuscar")
        self.actionLIBRO_MAYOR = QtWidgets.QAction(MainWindow)
        self.actionLIBRO_MAYOR.setObjectName("actionLIBRO_MAYOR")
        self.actionNuevo_2 = QtWidgets.QAction(MainWindow)
        self.actionNuevo_2.setObjectName("actionNuevo_2")
        self.actionBuscar_2 = QtWidgets.QAction(MainWindow)
        self.actionBuscar_2.setObjectName("actionBuscar_2")
        self.actionLibro_Mayor_2 = QtWidgets.QAction(MainWindow)
        self.actionLibro_Mayor_2.setObjectName("actionLibro_Mayor_2")
        self.actionNueva_Cuenta = QtWidgets.QAction(MainWindow)
        self.actionNueva_Cuenta.setObjectName("actionNueva_Cuenta")
        self.actionInflacion = QtWidgets.QAction(MainWindow)
        self.actionInflacion.setObjectName("actionInflacion")
        self.menuCLIENTE.addAction(self.actionClientes)
        self.menuCuentas.addAction(self.actionBuscar_Cuenta)
        self.menuASIENTOS.addAction(self.actionEjercicio)
        self.menuASIENTOS.addAction(self.actionNuevo_Ejercicio)
        self.menuASIENTOS.addAction(self.menuCuentas.menuAction())
        self.menuASIENTOS.addAction(self.actionAsiento)
        self.menuASIENTOS.addAction(self.actionPlan_Cuentas)
        self.menuASIENTOS.addAction(self.actionInflacion)
        self.menuREPORTES.addAction(self.actionLibro_Diario_General)
        self.menuREPORTES.addAction(self.actionSumas_y_Saldos)
        self.menuREPORTES.addAction(self.actionLibro_Mayor_2)
        self.menuCUENTAS.addAction(self.actionAlta_de_proveedores)
        self.menuLibro_IVA_Compras.addAction(self.actionNuevo_2)
        self.menuLibro_IVA_Compras.addAction(self.actionBuscar)
        self.menuLibro_IVA_Ventas.addAction(self.actionNuevo)
        self.menuLibro_IVA_Ventas.addAction(self.actionBuscar_2)
        self.menuLIBROS.addSeparator()
        self.menuLIBROS.addAction(self.menuLibro_IVA_Compras.menuAction())
        self.menuLIBROS.addAction(self.menuLibro_IVA_Ventas.menuAction())
        self.menuBar.addAction(self.menuCLIENTE.menuAction())
        self.menuBar.addAction(self.menuASIENTOS.menuAction())
        self.menuBar.addAction(self.menuLIBROS.menuAction())
        self.menuBar.addAction(self.menuCUENTAS.menuAction())
        self.menuBar.addAction(self.menuREPORTES.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btn_clientes, self.btn_ejercicios)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Menu de inicio"))
        self.menuCLIENTE.setTitle(_translate("MainWindow", "Clientes"))
        self.menuASIENTOS.setTitle(_translate("MainWindow", "Ejercicios"))
        self.menuCuentas.setTitle(_translate("MainWindow", "Cuentas"))
        self.menuREPORTES.setTitle(_translate("MainWindow", "Reportes"))
        self.menuCUENTAS.setTitle(_translate("MainWindow", "Proveedores / Clientes"))
        self.menuLIBROS.setTitle(_translate("MainWindow", "Libros"))
        self.menuLibro_IVA_Compras.setTitle(_translate("MainWindow", "Libro IVA Compras"))
        self.menuLibro_IVA_Ventas.setTitle(_translate("MainWindow", "Libro IVA Ventas"))
        self.actionEjercicio.setText(_translate("MainWindow", "Buscar  Ejercicio "))
        self.actionLIBRO_DIARIO.setText(_translate("MainWindow", "Libro diario"))
        self.actionClientes.setText(_translate("MainWindow", "Clientes / Empresa"))
        self.actionNuevo_Ejercicio.setText(_translate("MainWindow", "Nuevo Ejercicio"))
        self.actionLibro_IVA_Ventas.setText(_translate("MainWindow", "Libro IVA Ventas"))
        self.actionLibro_IVA_Compras.setText(_translate("MainWindow", "Libro IVA Compras"))
        self.actionLibro_Mayor.setText(_translate("MainWindow", "Libro Mayor"))
        self.actionLibro_Diario_General.setText(_translate("MainWindow", "Libro Diario General"))
        self.actionSumas_y_Saldos.setText(_translate("MainWindow", "Sumas y Saldos"))
        self.actionAlta_de_proveedores.setText(_translate("MainWindow", "Alta de proveedores / clientes"))
        self.actionNuevo.setText(_translate("MainWindow", "Nuevo"))
        self.actionBuscar_Cuenta.setText(_translate("MainWindow", "Buscar Cuenta"))
        self.actionPlan_Cuentas.setText(_translate("MainWindow", "Plan de Cuentas"))
        self.actionAsiento.setText(_translate("MainWindow", "Asiento"))
        self.actionBuscar.setText(_translate("MainWindow", "Buscar"))
        self.actionLIBRO_MAYOR.setText(_translate("MainWindow", "LIBRO MAYOR"))
        self.actionNuevo_2.setText(_translate("MainWindow", "Nuevo"))
        self.actionBuscar_2.setText(_translate("MainWindow", "Buscar"))
        self.actionLibro_Mayor_2.setText(_translate("MainWindow", "Libro Mayor"))
        self.actionNueva_Cuenta.setText(_translate("MainWindow", "Nueva Cuenta"))
        self.actionInflacion.setText(_translate("MainWindow", "Inflacion"))

